# -*- coding: utf-8 -*-
import os, json

OUT_DIR = r"D:\AI\readbook\picture-books\raz-t-quiz\_quizdata"
os.makedirs(OUT_DIR, exist_ok=True)

# ---------------------------------------------------------------
# 1. thomas-jefferson
# ---------------------------------------------------------------
thomas = {
    "slug": "thomas-jefferson",
    "title": "Thomas Jefferson",
    "titleZh": "托马斯·杰斐逊",
    "level": "T",
    "genre": "Biography",
    "mainSkill": "Key Ideas and Details",
    "questions": [
        {"q": {"en": "What was unusual about the presidential election of 1800?", "zh": "1800年的总统大选有什么不寻常之处？"},
         "options": [{"en": "No winner was declared until the House voted 36 times over two months", "zh": "直到众议院投票36次、耗时两个多月才确定赢家"},
                     {"en": "Thomas Jefferson won on the very first ballot", "zh": "托马斯·杰斐逊在第一轮投票中就赢得了选举"},
                     {"en": "George Washington was elected for a third term", "zh": "乔治·华盛顿当选第三届总统"},
                     {"en": "The election was canceled because of a tie", "zh": "因为平票，选举被取消了"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Four candidates ran, and after the votes were counted there was no winner. The House of Representatives voted thirty-six times over more than two months before Jefferson was declared the winner.", "zh": "四位候选人参选，计票后没有赢家。众议院在两个多月里投票三十六次，才宣布杰斐逊获胜。"}},
        {"q": {"en": "Who insisted that Jefferson write the Declaration of Independence?", "zh": "是谁坚持让杰斐逊来撰写《独立宣言》的？"},
         "options": [{"en": "John Adams", "zh": "约翰·亚当斯"}, {"en": "George Washington", "zh": "乔治·华盛顿"}, {"en": "Benjamin Franklin", "zh": "本杰明·富兰克林"}, {"en": "Thomas Paine", "zh": "托马斯·潘恩"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "At the Second Continental Congress, John Adams knew Jefferson was an exceptional writer and insisted that Jefferson draft the Declaration of Independence.", "zh": "在第二届大陆会议上，约翰·亚当斯深知杰斐逊文笔出众，坚持要他起草《独立宣言》。"}},
        {"q": {"en": "Which famous phrase did Jefferson include in the Declaration of Independence?", "zh": "杰斐逊在《独立宣言》中写下了哪句著名的话？"},
         "options": [{"en": "\"all men are created equal... Life, Liberty and the pursuit of Happiness\"", "zh": "“人人生而平等……享有生命、自由和对幸福的追求”"},
                     {"en": "\"give me liberty or give me death\"", "zh": "“不自由，毋宁死”"},
                     {"en": "\"a government of the people, by the people\"", "zh": "“民有、民治的政府”"},
                     {"en": "\"we have nothing to fear but fear itself\"", "zh": "“我们唯一要害怕的就是害怕本身”"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "The book quotes Jefferson's words: \"We hold these truths to be self-evident, that all men are created equal, that they are endowed... with... Life, Liberty and the pursuit of Happiness.\"", "zh": "书中引用了杰斐逊的话：“我们认为这些真理是不言而喻的：人人生而平等，造物主赋予他们……生命、自由和对幸福的追求。”"}},
        {"q": {"en": "What was Monticello?", "zh": "蒙蒂塞洛（Monticello）是什么？"},
         "options": [{"en": "The dream home Jefferson designed and built on a Virginia mountaintop", "zh": "杰斐逊在弗吉尼亚一座山顶上自己设计、建造的梦想之家"},
                     {"en": "The British palace he lived in as a child", "zh": "他小时候居住的英国宫殿"},
                     {"en": "The school where he studied law", "zh": "他学习法律的学校"},
                     {"en": "The ship that carried him to Europe", "zh": "载他去欧洲的那艘船"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "In 1769 Jefferson began building his dream home on a mountaintop in Virginia. He designed it himself, named it Monticello, and kept improving it for forty years.", "zh": "1769年，杰斐逊在弗吉尼亚的一座山顶上开始建造他的梦想之家，亲自设计，取名蒙蒂塞洛，并持续改建了四十年。"}},
        {"q": {"en": "What did the Louisiana Purchase do for the United States in 1803?", "zh": "1803年的“路易斯安那购地”给美国带来了什么？"},
         "options": [{"en": "It doubled the country's size by buying land from France", "zh": "它从法国购买土地，使国家面积扩大了一倍"},
                     {"en": "It ended the Revolutionary War", "zh": "它结束了独立战争"},
                     {"en": "It freed Jefferson's slaves", "zh": "它解放了杰斐逊的奴隶"},
                     {"en": "It created the first public school", "zh": "它建立了第一所公立学校"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "In 1803 Jefferson doubled the country's size with the Louisiana Purchase from France, extending the western border to the Rocky Mountains. It was the first time so much land was exchanged by two countries without war.", "zh": "1803年，杰斐逊从法国购得路易斯安那，使国家面积扩大一倍，西部边界延伸至落基山脉。这是历史上首次两国不通过战争就交换如此大片土地。"}},
        {"q": {"en": "How did Jefferson help the Library of Congress after the British burned it?", "zh": "在英军烧毁国会图书馆后，杰斐逊是如何帮忙的？"},
         "options": [{"en": "He sold his own collection of 6,487 books to reopen it", "zh": "他卖掉了自己6487册藏书，让图书馆重新开放"},
                     {"en": "He rebuilt the building with his own money", "zh": "他自掏腰包重建了馆舍"},
                     {"en": "He wrote new books to replace the lost ones", "zh": "他写新书来替代被毁的书籍"},
                     {"en": "He became its first librarian", "zh": "他成为了首任馆长"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "During the War of 1812 the British burned the Library of Congress. In 1815 Jefferson sold his personal collection of 6,487 books so the library could reopen.", "zh": "1812年战争中英军烧毁了国会图书馆。1815年，杰斐逊卖掉自己6487册的私人藏书，使图书馆得以重新开放。"}},
        {"q": {"en": "What does the book say about Jefferson and slavery?", "zh": "关于杰斐逊与奴隶制，书中是怎么说的？"},
         "options": [{"en": "He believed slavery was wrong but never freed his own slaves", "zh": "他认为奴隶制是错误的，却从未解放自己的奴隶"},
                     {"en": "He freed all his slaves when he became president", "zh": "他当上总统后解放了所有奴隶"},
                     {"en": "He never owned any slaves", "zh": "他从未拥有过奴隶"},
                     {"en": "He wrote the law that ended slavery", "zh": "他起草了废除奴隶制的法律"}],
         "answer": 0, "skill": "Author's Purpose and Perspective",
         "explain": {"en": "The book states that Jefferson believed slavery was wrong, but he never freed his slaves. Slavery was abolished in the United States in 1865, thirty-nine years after he died.", "zh": "书中说杰斐逊认为奴隶制是错误的，却从未解放自己的奴隶。美国于1865年（他去世39年后）才废除奴隶制。"}},
        {"q": {"en": "What did Jefferson believe about where government power should lie?", "zh": "杰斐逊认为政府权力应当集中在哪里？"},
         "options": [{"en": "The individual states should have the strongest power", "zh": "各州应当拥有最大的权力"},
                     {"en": "A king should hold all the power", "zh": "国王应当掌握全部权力"},
                     {"en": "Great Britain should rule the colonies", "zh": "英国应当统治殖民地"},
                     {"en": "The president should have total control", "zh": "总统应当拥有绝对控制权"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Jefferson argued with John Adams about government. Adams wanted a strong central government; Jefferson believed the individual states should have the strongest powers.", "zh": "杰斐逊与约翰·亚当斯在政府形式上意见相左。亚当斯主张强大的中央政府，而杰斐逊认为各州应拥有最大权力。"}},
        {"q": {"en": "How long did Jefferson serve as president?", "zh": "杰斐逊担任了多久的总统？"},
         "options": [{"en": "Two terms, for a total of eight years", "zh": "两届，共八年"}, {"en": "One term of four years", "zh": "一届，四年"}, {"en": "Three terms, for a total of twelve years", "zh": "三届，共十二年"}, {"en": "Less than one year", "zh": "不到一年"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "In 1801 Jefferson became the third president and served two terms for a total of eight years, cutting the country's debt in half during that time.", "zh": "1801年杰斐逊成为美国第三任总统，连任两届共八年，期间把国家债务削减了一半。"}},
        {"q": {"en": "When did Thomas Jefferson die, and what was notable about that date?", "zh": "托马斯·杰斐逊何时去世？那个日期有什么特别？"},
         "options": [{"en": "July 4, 1826, the same day as John Adams and the nation's 50th birthday", "zh": "1826年7月4日，与约翰·亚当斯同日去世，也是美国建国50周年"},
                     {"en": "December 3, 1800, Election Day", "zh": "1800年12月3日，大选日"},
                     {"en": "July 4, 1776, Independence Day", "zh": "1776年7月4日，独立日"},
                     {"en": "January 1, 1772, his wedding day", "zh": "1772年1月1日，他的结婚日"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Thomas Jefferson died on July 4, 1826, the same day as John Adams and exactly fifty years after the Declaration of Independence was approved.", "zh": "托马斯·杰斐逊于1826年7月4日去世，与约翰·亚当斯同日，也正好是《独立宣言》通过五十周年。"}},
    ],
    "extended": {"prompt": {"en": "Thomas Jefferson wrote that 'all men are created equal' yet he owned slaves his whole life. Can someone do great things for a country while still making serious mistakes? Explain your view.", "zh": "托马斯·杰斐逊写下“人人生而平等”，却终其一生都拥有奴隶。你认为一个人既能为国家做出伟大贡献，又同时犯下严重错误吗？说说你的看法。"},
                 "guidance": {"en": ["List both Jefferson's achievements (Declaration, Louisiana Purchase) and his contradiction (owning slaves).", "Think about whether one person's good deeds and bad choices can both be true at the same time."],
                              "zh": ["列出杰斐逊的成就（独立宣言、路易斯安那购地）和他前后矛盾的行为（拥有奴隶）。", "思考一个人的善行与错误选择是否可以同时成立。"]}},
}

# ---------------------------------------------------------------
# 2. the-return-to-the-hollow-part-i
# ---------------------------------------------------------------
hollow1 = {
    "slug": "the-return-to-the-hollow-part-i",
    "title": "The Return to the Hollow (Part I)",
    "titleZh": "重返空心镇（第一部）",
    "level": "T",
    "genre": "Narrative",
    "mainSkill": "Key Ideas and Details",
    "questions": [
        {"q": {"en": "Why are the girls decorating the cafeteria for the Halloween party?", "zh": "女孩们为什么要在食堂为万圣节派对布置场地？"},
         "options": [{"en": "It is their punishment for sneaking into the attic", "zh": "这是她们偷偷溜进阁楼的惩罚"},
                     {"en": "They volunteered to help Principal Taylor", "zh": "她们自愿帮助泰勒校长"},
                     {"en": "They won a contest at school", "zh": "她们在学校比赛中获胜"},
                     {"en": "They are paid to do it", "zh": "她们是拿工钱做这件事的"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "The librarian told Principal Taylor about their unauthorized trip into the attic, so helping decorate for the Halloween party is their punishment.", "zh": "图书管理员把她们擅自闯入阁楼的事告诉了泰勒校长，所以帮忙布置万圣节派对是给她们的惩罚。"}},
        {"q": {"en": "What did Sarah discover about the journal found in her dad's office?", "zh": "关于在父亲办公室发现的日记，萨拉发现了什么？"},
         "options": [{"en": "It belonged to her mother", "zh": "那是她母亲的日记"},
                     {"en": "It belonged to Principal Taylor", "zh": "那是泰勒校长的"},
                     {"en": "It was written by the librarian", "zh": "那是图书管理员写的"},
                     {"en": "It was a library book", "zh": "那是一本图书馆的书"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Sarah examined the handwriting and found it similar to a letter her mother wrote, and her mother's name is written inside the cover, so the journal belonged to her mom.", "zh": "萨拉仔细辨认笔迹，发现它和母亲写的一封信很相似，而且封面内写着母亲的名字，所以这本日记属于她妈妈。"}},
        {"q": {"en": "What connection did they find between the mother's journal and the library book?", "zh": "她们发现母亲的日记和图书馆那本书之间有什么关联？"},
         "options": [{"en": "The loose pages in the journal are the book's missing pages", "zh": "日记里散落的页正是那本书缺失的页"},
                     {"en": "The journal was printed by the library", "zh": "日记是图书馆印刷的"},
                     {"en": "The book was written by the mother", "zh": "那本书是母亲写的"},
                     {"en": "There was no connection at all", "zh": "两者之间毫无关联"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "The narrator realizes the loose pages inside the mother's notebook are the missing pages torn out of the library book.", "zh": "叙述者发现母亲笔记本里散落的页，正是从图书馆那本书中撕下、缺失的页。"}},
        {"q": {"en": "According to the torn pages, what happened at Porter's Mill?", "zh": "根据撕下的书页，空心镇（Porter's Mill）发生了什么？"},
         "options": [{"en": "A geologic event changed the river, the mill owner's wife died, and the family disappeared", "zh": "一次地质事件改变了河道，磨坊主妻子去世，一家人就此消失"},
                     {"en": "A fire burned the whole town down", "zh": "一场大火把整座镇子烧光了"},
                     {"en": "A festival was held there every year", "zh": "那里每年都举办节日庆典"},
                     {"en": "The town became a big city", "zh": "那座镇子变成了一座大城市"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "The pages say a geologic event changed the river's path, John Porter's wife died, the adopted children were devastated, plans to relocate the mill were canceled, and the family stopped appearing in town.", "zh": "书页上说，一次地质事件改变了河道，约翰·波特的妻子去世，养子女悲痛欲绝，搬迁磨坊的计划取消，这家人也不再在镇上露面。"}},
        {"q": {"en": "What did Aunt Terra reveal about Sarah's mother and Jasper?", "zh": "泰拉姨妈透露了萨拉的母亲的贾斯珀（Jasper）之间的什么事？"},
         "options": [{"en": "They were best friends; Jasper disappeared and Anna searched for him", "zh": "她们是挚友；贾斯珀失踪后，安娜（母亲）一直在寻找他"},
                     {"en": "They were enemies who never spoke", "zh": "她们是敌人，从不说话"},
                     {"en": "They had never met", "zh": "她们从未见过面"},
                     {"en": "They were sisters", "zh": "她们是姐妹"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Aunt Terra explains that Anna (Sarah's mother) was best friends with Qynn's Uncle Jasper. When Jasper disappeared, Anna was determined to find him.", "zh": "泰拉姨妈说，安娜（萨拉的母亲的）和昆（Qynn）的叔叔贾斯珀是挚友。贾斯珀失踪后，安娜下定决心要找到他。"}},
        {"q": {"en": "What items did Anna bring back from Porter's Mill?", "zh": "安娜从空心镇带回了哪些东西？"},
         "options": [{"en": "The key, scissors, and lantern that belonged to John Porter", "zh": "属于约翰·波特的钥匙、剪刀和提灯"},
                     {"en": "A map of the whole world", "zh": "一张世界地图"},
                     {"en": "A bag of gold coins", "zh": "一袋金币"},
                     {"en": "Her mother's journal", "zh": "她母亲的日记"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Anna came back with the key, scissors, and lantern, which she said had belonged to John Porter and his wife, along with an old map of Porter's Mill.", "zh": "安娜带着钥匙、剪刀和提灯回来，她说这些东西原属于约翰·波特和他的妻子，还有一张空心镇的旧地图。"}},
        {"q": {"en": "What phrase was repeated again and again in Anna's research notes?", "zh": "安娜的研究笔记中反复出现的是哪句话？"},
         "options": [{"en": "\"Keep moving forward. Make sure everything is in its place.\"", "zh": "“一直向前走。确保一切都各归其位。”"},
                     {"en": "\"Run as fast as you can\"", "zh": "“能跑多快就跑多快”"},
                     {"en": "\"Never trust strangers\"", "zh": "“永远不要相信陌生人”"},
                     {"en": "\"Hide and wait\"", "zh": "“躲起来等待”"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "The narrator reads that Anna's notes repeat, over and over, 'Keep moving forward. Make sure everything is in its place.'", "zh": "叙述者读到，安娜的笔记里一遍又一遍地重复着：“一直向前走。确保一切都各归其位。”"}},
        {"q": {"en": "What did the old map of the Hollow show about the river?", "zh": "那张空心镇的旧地图上，河流是怎样的？"},
         "options": [{"en": "The river ran right through the middle, not around the woods", "zh": "河流从正中间穿过，而不是绕林而行"},
                     {"en": "The river had dried up completely", "zh": "河流已经完全干涸"},
                     {"en": "There was no river on the map", "zh": "地图上根本没有河"},
                     {"en": "The river flowed backward", "zh": "河流是倒着流的"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "Sarah circles a mark on the map; the river does not run in its usual path around the woods but right through the middle of the Hollow and Porter's Mill.", "zh": "萨拉在地图上圈出一个标记；河流并没有像平时那样绕林而行，而是从空心镇和空心镇的正中间穿过。"}},
        {"q": {"en": "Who is the narrator of the story?", "zh": "这个故事的叙述者是谁？"},
         "options": [{"en": "Qynn, the girl whose Uncle Jasper disappeared", "zh": "昆（Qynn），那个叔叔贾斯珀失踪的女孩"},
                     {"en": "Sarah's mother, Anna", "zh": "萨拉的母亲的安娜"},
                     {"en": "Principal Taylor", "zh": "泰勒校长"},
                     {"en": "The boy from the Hollow", "zh": "空心镇那个男孩"}],
         "answer": 0, "skill": "Author's Purpose and Perspective",
         "explain": {"en": "Aunt Terra says Anna was best friends with 'Qynn's Uncle Jasper,' and the narrator later says 'This is my Uncle Jasper's!', so the narrator is Qynn.", "zh": "泰拉姨妈说安娜和“昆的叔叔贾斯珀”是挚友，而叙述者后来说“这是我叔叔贾斯珀的！”，所以叙述者就是昆。"}},
        {"q": {"en": "What decision do the girls make at the end of Part I?", "zh": "第一部结尾，女孩们做出了什么决定？"},
         "options": [{"en": "They decide to go into the Hollow the next night to find Porter's Mill", "zh": "她们决定第二天夜里进入空心镇，去寻找空心镇"},
                     {"en": "They decide to tell Principal Taylor everything", "zh": "她们决定把一切告诉泰勒校长"},
                     {"en": "They decide to forget about the mystery", "zh": "她们决定不再管这个谜团"},
                     {"en": "They decide to move to Nepal", "zh": "她们决定搬到尼泊尔去"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "After hearing Aunt Terra's story, Sarah says, 'We have to go into the Hollow tomorrow night and find Porter's Mill.' The chapter ends 'To be continued...'", "zh": "听完泰拉姨妈的故事，萨拉说：“我们明天夜里必须进入空心镇，找到空心镇。”章节以“待续……”结尾。"}},
    ],
    "extended": {"prompt": {"en": "The narrator says 'Things are lining up a bit too well for me to accept coincidence as an excuse.' Based on the clues in Part I, what do you predict the girls will find in the Hollow?", "zh": "叙述者说“种种线索吻合得太好了，我无法用巧合来解释”。根据第一部的线索，你预测女孩们在空心镇会找到什么？"},
                 "guidance": {"en": ["Review the clues: the map, the key, the scissors, the lantern, and Anna's notes.", "Use those clues to make a prediction and explain why you think so."],
                              "zh": ["回顾这些线索：地图、钥匙、剪刀、提灯，以及安娜的笔记。", "用这些线索做出预测，并说明你为什么这样想。"]}},
}

# ---------------------------------------------------------------
# 3. the-return-to-the-hollow-part-ii
# ---------------------------------------------------------------
hollow2 = {
    "slug": "the-return-to-the-hollow-part-ii",
    "title": "The Return to the Hollow (Part II)",
    "titleZh": "重返空心镇（第二部）",
    "level": "T",
    "genre": "Narrative",
    "mainSkill": "Key Ideas and Details",
    "questions": [
        {"q": {"en": "When do the events of Part II take place?", "zh": "第二部发生在什么时候？"},
         "options": [{"en": "On Halloween night, the night after decorating the cafeteria", "zh": "万圣节之夜，也就是布置食堂的那天晚上"},
                     {"en": "On Christmas morning", "zh": "在圣诞节的早晨"},
                     {"en": "During summer vacation", "zh": "在暑假期间"},
                     {"en": "On the first day of school", "zh": "在开学第一天"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "The girls decorated for 'tomorrow's Halloween party' as punishment, and Part II opens with them about to go into the Hollow on Halloween night.", "zh": "女孩们因为惩罚而布置“明天的万圣节派对”，第二部开头她们正准备在万圣节之夜进入空心镇。"}},
        {"q": {"en": "What did Sarah use to cut through the spider webs covering the opening?", "zh": "萨拉用什么割开了挡住入口的蜘蛛网？"},
         "options": [{"en": "The scissors from her backpack", "zh": "她背包里的剪刀"},
                     {"en": "A sharp stick", "zh": "一根尖树枝"},
                     {"en": "Jake's flashlight", "zh": "杰克的手电筒"},
                     {"en": "The boy's hands", "zh": "男孩的双手"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Sarah unzips the narrator's backpack, steps forward, and uses the scissors to snip her way through the strong webs covering the opening.", "zh": "萨拉拉开叙述者的背包，走上前，用剪刀一路剪开挡住入口的结实蛛网。"}},
        {"q": {"en": "The 'wall of dark leaves' is compared to what?", "zh": "那道“暗叶墙”被比作什么？"},
         "options": [{"en": "A river, because it twists and turns", "zh": "一条河，因为它弯弯曲曲"},
                     {"en": "A brick wall", "zh": "一道砖墙"},
                     {"en": "A tall building", "zh": "一座高楼"},
                     {"en": "A curtain", "zh": "一块窗帘"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "Sarah interrupts the narrator to say the twisting, turning wall of leaves is 'almost like—a river.' The wall appears and disappears through the trees like a winding river.", "zh": "萨拉打断叙述者，说这道弯弯曲曲的暗叶墙“简直像——一条河”。这道墙在树林间时隐时现，如同蜿蜒的河流。"}},
        {"q": {"en": "How did Jake start the fire to light the lantern?", "zh": "杰克是怎样生火点亮提灯的？"},
         "options": [{"en": "By scraping two rocks together to make sparks", "zh": "用两块石头相互刮擦，迸出火花"},
                     {"en": "By using a box of matches", "zh": "用一盒火柴"},
                     {"en": "By rubbing two sticks together", "zh": "用两根木棍相互摩擦"},
                     {"en": "By pressing a lighter button", "zh": "按打火机的按钮"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Jake says he learned from a book how to start a fire in an emergency. He scrapes two plain rocks together, and after a few tries a flame catches the oil-soaked wick.", "zh": "杰克说他从书里学过紧急生火的方法。他用两块普通的石头相互刮擦，试了几次后，火苗点着了浸油的灯芯。"}},
        {"q": {"en": "Which clues from Part I help the girls in Part II?", "zh": "第一部的哪些线索在第二部中帮到了女孩们？"},
         "options": [{"en": "'Keep moving forward' and 'Everything in its place,' plus the scissors, lantern, and map", "zh": "“一直向前走”和“一切都各归其位”，还有剪刀、提灯和地图"},
                     {"en": "A magic spell and a fairy wand", "zh": "一句魔咒和一根仙女魔杖"},
                     {"en": "Principal Taylor's permission slip", "zh": "泰勒校长的同意条"},
                     {"en": "A phone number for Aunt Terra", "zh": "泰拉姨妈的电话号码"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "Anna's notes ('Keep moving forward,' 'Everything in its place') guide them; the scissors cut the webs, the lantern is lit and hung, and the map shows the way.", "zh": "安娜的笔记（“一直向前走”“一切都各归其位”）指引着她们；剪刀割开蛛网，提灯被点亮挂起，地图指明方向。"}},
        {"q": {"en": "What did they find behind the vines on the giant tree?", "zh": "她们在那棵巨树缠绕的藤蔓后面发现了什么？"},
         "options": [{"en": "A metal hook to hang the lantern and a hidden door with a handle", "zh": "一个挂提灯的金属钩，以及一扇带把手的暗门"},
                     {"en": "A pile of gold treasure", "zh": "一堆黄金宝藏"},
                     {"en": "The boy's lost dog", "zh": "男孩丢失的狗"},
                     {"en": "A trap made of stones", "zh": "一个石头做的陷阱"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Pulling the thick vines, they grab something cold and hard: a metal hook. Lamplight then reveals a door handle they had not seen before.", "zh": "她们拉扯浓密的藤蔓，抓到一样又冷又硬的东西——一个金属挂钩。接着灯光照出了一直没被发现的门把手。"}},
        {"q": {"en": "Whose dog is Odie?", "zh": "奥迪（Odie）是谁的狗？"},
         "options": [{"en": "The narrator's (Qynn's) brother's dog", "zh": "叙述者（昆）的哥哥的狗"},
                     {"en": "Sarah's pet dog", "zh": "萨拉的宠物狗"},
                     {"en": "Principal Taylor's dog", "zh": "泰勒校长的狗"},
                     {"en": "The boy from the Hollow's dog", "zh": "空心镇那个男孩的狗"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "The text says 'Odie, my brother's dog' as the narrator speaks, so Odie belongs to the narrator's brother.", "zh": "文中叙述者说“奥迪，我哥哥的狗”，所以奥迪是叙述者哥哥的狗。"}},
        {"q": {"en": "What does the boy from the Hollow keep saying to urge the group onward?", "zh": "空心镇的男孩为了催促大家前进，一直重复说什么？"},
         "options": [{"en": "\"Keep moving forward\"", "zh": "“一直向前走”"},
                     {"en": "\"Go back home\"", "zh": "“回家去吧”"},
                     {"en": "\"Stay very still\"", "zh": "“保持别动”"},
                     {"en": "\"Hide in the leaves\"", "zh": "“躲进叶子里”"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Throughout Part II the boy calls 'Keep moving forward' as he leads them deeper into the Hollow, echoing Anna's notes from Part I.", "zh": "在整个第二部里，男孩一边把他们带向空心镇深处，一边喊着“一直向前走”，呼应了第一部里安娜的笔记。"}},
        {"q": {"en": "How would you describe the mood the author creates in Part II?", "zh": "你会如何形容作者在第二部中营造的氛围？"},
         "options": [{"en": "Scary and suspenseful, with darkness and laughter of unseen children", "zh": "恐怖而充满悬念，伴随着黑暗和看不见的孩子们的笑声"},
                     {"en": "Happy and cheerful", "zh": "快乐而欢快"},
                     {"en": "Calm and peaceful", "zh": "平静而安宁"},
                     {"en": "Boring and slow", "zh": "无聊而拖沓"}],
         "answer": 0, "skill": "Author's Purpose and Perspective",
         "explain": {"en": "The author uses dark woods, a twisting wall of leaves, and the laughter of unseen children to build a scary, suspenseful mood.", "zh": "作者用幽暗的树林、蜿蜒的暗叶墙，以及看不见的孩子们的笑声，营造出恐怖而悬念重重的氛围。"}},
        {"q": {"en": "What happens at the very end of Part II?", "zh": "第二部结尾发生了什么？"},
         "options": [{"en": "They find a door, crawl through the vines, and Sarah slams it shut as leaves move with little feet", "zh": "她们找到一扇门，爬过藤蔓钻进去，萨拉在叶子晃动、露出小脚时猛地关上门"},
                     {"en": "They are caught by Principal Taylor", "zh": "她们被泰勒校长抓住了"},
                     {"en": "They find Sarah's mother waiting", "zh": "她们发现萨拉的母亲的在等着她们"},
                     {"en": "They go home to bed", "zh": "她们回家睡觉了"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Sarah turns the handle and pushes the door open; Jake and Odie rush in. The narrator dives through as Sarah slams the door shut while the leaves beside her move with little feet.", "zh": "萨拉转动把手推开门；杰克和奥迪冲了进去。叙述者跟着钻过去，萨拉在身旁的叶子露出小脚时猛地把门关上。"}},
    ],
    "extended": {"prompt": {"en": "The story ends with the girls safe behind a closed door, but something with 'little feet' is moving in the leaves. What do you think is on the other side of the door, and what will happen next?", "zh": "故事以女孩们关上门后安全脱身为结尾，但叶子里有“小脚”在动。你认为门的另一边是什么，接下来又会发生什么？"},
                 "guidance": {"en": ["Think about the laughing children heard throughout the story.", "Connect the 'little feet' to a clue from earlier in the book."],
                              "zh": ["想想贯穿全书的那些欢笑的孩子们。", "把“小脚”和书中更早出现的某个线索联系起来。"]}},
}

# ---------------------------------------------------------------
# 4. the-return-to-the-hollow-part-iii
# ---------------------------------------------------------------
hollow3 = {
    "slug": "the-return-to-the-hollow-part-iii",
    "title": "The Return to the Hollow (Part III)",
    "titleZh": "重返空心镇（第三部）",
    "level": "T",
    "genre": "Narrative",
    "mainSkill": "Key Ideas and Details",
    "questions": [
        {"q": {"en": "Where do the characters end up after jumping through the hidden door?", "zh": "她们跳过那扇暗门后，来到了什么地方？"},
         "options": [{"en": "Porter's Mill, a large curved room with a wrapping staircase", "zh": "空心镇，一个带环形楼梯的弧形大房间"},
                     {"en": "The school cafeteria", "zh": "学校食堂"},
                     {"en": "Sarah's house", "zh": "萨拉的家里"},
                     {"en": "A cave by the lake", "zh": "湖边的一个山洞"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "After jumping through the hidden door, the group lands in a large curved room with a staircase wrapping around the wall. Sarah whispers, 'Porter's Mill.'", "zh": "跳过暗门后，大家落在一个带环形楼梯的弧形大房间里。萨拉低声说：“这是空心镇。”"}},
        {"q": {"en": "What does Sarah find upstairs that belonged to her mother?", "zh": "萨拉在楼上发现了什么，那是属于她母亲的东西？"},
         "options": [{"en": "A pendant with photos of her dad and baby Sarah", "zh": "一个吊坠，里面有她父亲和婴儿萨拉的合影"},
                     {"en": "A map of the whole town", "zh": "一张全镇地图"},
                     {"en": "A bag of gold coins", "zh": "一袋金币"},
                     {"en": "A pair of scissors", "zh": "一把剪刀"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Sarah finds a pendant and opens it to reveal two aged photos: a younger version of her dad and a baby with thick black curly hair, which she says is herself and was her mother's.", "zh": "萨拉找到一个吊坠，打开后看到两张泛黄的照片：年轻时的父亲，和一个长着浓密黑色卷发的婴儿——她说那就是自己，吊坠原是母亲的。"}},
        {"q": {"en": "Who are the ghost children, and what do they apologize for?", "zh": "那些幽灵孩子是谁，他们为什么道歉？"},
         "options": [{"en": "Children who scared the group for fun, calling it cruel", "zh": "那些为了好玩而吓唬她们的孩子们，承认那很残忍"},
                     {"en": "Sarah's old classmates", "zh": "萨拉从前的同学"},
                     {"en": "The school teachers", "zh": "学校的老师们"},
                     {"en": "The narrator's family", "zh": "叙述者的家人"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "The children who chased them apologize, saying they thought scaring the group would be fun but it was cruel, and they needed help getting into Porter's Mill.", "zh": "一直追着她们的孩子们道歉说，本以为吓唬她们很好玩，但其实很残忍；而且他们需要帮忙才能进入空心镇。"}},
        {"q": {"en": "What do the papers found in the cupboard reveal?", "zh": "在橱柜里找到的那些纸说明了什么？"},
         "options": [{"en": "They were written by Uncle Jasper, saying he stepped through a door and may not return", "zh": "那是贾斯珀叔叔写的，说他走进了某扇门，可能再也不回来"},
                     {"en": "They are a school homework assignment", "zh": "那是一份学校作业"},
                     {"en": "They list the town's rules", "zh": "那上面列着镇上的规矩"},
                     {"en": "They are a recipe book", "zh": "那是一本食谱"}],

         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "The back page reads that the writer is about to step through the door and, if not returned, to tell his brother, wife, and niece Qynn he loves them. The narrator recognizes Uncle Jasper's signature.", "zh": "最后一页写道，写纸条的人正要走进那扇门，如果没能回来，请转告他的兄弟、妻子和侄女昆，他非常爱她们。叙述者认出那是贾斯珀叔叔的签名。"}},
        {"q": {"en": "How does Part III connect to the mystery about Jasper from Part I?", "zh": "第三部如何呼应第一部中关于贾斯珀的谜团？"},
         "options": [{"en": "Jasper's note proves he went through the door at Porter's Mill and never returned", "zh": "贾斯珀的纸条证实他走进了空心镇的那扇门，再没回来"},
                     {"en": "It shows Jasper moved to Nepal", "zh": "它说明贾斯珀搬去了尼泊尔"},
                     {"en": "It says Jasper became a teacher", "zh": "它说贾斯珀当上了一名老师"},
                     {"en": "It reveals Jasper was a stranger", "zh": "它揭示贾斯珀是个陌生人"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "Part I said Anna searched for the missing Jasper at Porter's Mill; Part III shows his note left at that very door, confirming he disappeared through it.", "zh": "第一部说安娜在空心镇寻找失踪的贾斯珀；第三部展示了他留在那扇门边的纸条，证实他正是从那里消失的。"}},
        {"q": {"en": "What is 'the Cave of the Lost'?", "zh": "“迷失洞（Cave of the Lost）”是什么地方？"},
         "options": [{"en": "The tunnel where they had previously found the key", "zh": "他们之前找到那把钥匙的隧道"},
                     {"en": "Sarah's secret hideout", "zh": "萨拉的秘密藏身地"},
                     {"en": "The school basement", "zh": "学校的地下室"},
                     {"en": "A room inside Porter's Mill", "zh": "空心镇里的一个房间"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Running through the rock passageway, Jake shines his light and says, 'Hey, we've been here before! It's the Cave of the Lost' — where they found the key.", "zh": "在岩石通道里奔跑时，杰克用手电筒照了照说：“嘿，我们来过这儿！这是迷失洞。”——也就是他们找到钥匙的地方。"}},
        {"q": {"en": "How did they open the ornately carved door?", "zh": "他们是怎么打开那扇雕刻精美的门的？"},
         "options": [{"en": "By putting the key in a small hole near the water and turning it", "zh": "把钥匙插进水边的小孔里转动"},
                     {"en": "By saying a magic word", "zh": "念一句魔咒"},
                     {"en": "By pushing it with all their strength", "zh": "用尽全力去推"},
                     {"en": "By lighting a fire in front of it", "zh": "在门前生一堆火"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Feeling around in the freezing water, the narrator finds a small keyhole-sized hole, inserts the key, turns it, and the stone crumbles to reveal a carved door.", "zh": "叙述者在冰冷的水里摸索，找到一个钥匙孔大小的小洞，插入钥匙转动，石头崩落，露出一扇雕刻的门。"}},
        {"q": {"en": "When Thomas says 'We're older than we look,' what does he mean?", "zh": "当托马斯说“我们比看上去要年长”时，他是什么意思？"},
         "options": [{"en": "The children are ghosts or spirits from long ago", "zh": "那些孩子是多年前的幽灵或魂魄"},
                     {"en": "They are grown-ups in costumes", "zh": "他们是穿着戏服的成年人"},
                     {"en": "They are the teachers", "zh": "他们是老师"},
                     {"en": "They are twins", "zh": "他们是双胞胎"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "Thomas means the children died years ago, so although they look like children, they are actually spirits much older than their appearance.", "zh": "托马斯的意思是，这些孩子多年前就已死去，所以虽然看起来像孩子，其实是比外表年长得多的魂魄。"}},
        {"q": {"en": "Why does the story end with the characters stepping through the door?", "zh": "为什么故事的结尾是角色们走进那扇门？"},
         "options": [{"en": "To create suspense, leaving their fate unknown", "zh": "为了制造悬念，让他们的命运悬而未决"},
                     {"en": "To show they went home", "zh": "为了表明他们回家了"},
                     {"en": "To end the book happily", "zh": "为了给书一个圆满结局"},
                     {"en": "To explain the mystery fully", "zh": "为了把谜团彻底解释清楚"}],
         "answer": 0, "skill": "Author's Purpose and Perspective",
         "explain": {"en": "Jake opens the door, yellow light fills the cave, and he and Odie vanish. The others hold hands and step through, falling — leaving readers in suspense.", "zh": "杰克打开门，黄光充满山洞，他和奥迪消失不见。其余人手拉手走进门里、坠了下去——让读者悬着心。"}},
        {"q": {"en": "What happens to Jake and Odie when the door opens?", "zh": "门打开时，杰克和奥迪发生了什么？"},
         "options": [{"en": "They disappear into the yellow light", "zh": "他们消失在黄光之中"},
                     {"en": "They run back home", "zh": "他们跑回家去了"},
                     {"en": "They hide behind a rock", "zh": "他们躲到石头后面"},
                     {"en": "They fall asleep", "zh": "他们睡着了"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "As Jake opens the door, the cave fills with yellow light, and by the time their eyes adjust, he and Odie are gone.", "zh": "杰克打开门时，山洞充满黄光；等大家眼睛适应过来，他和奥迪已经不见了。"}},
    ],
    "extended": {"prompt": {"en": "The trilogy ends with the characters falling through a mysterious door. What do you think is on the other side, and how might it bring the families back together?", "zh": "三部曲以角色们穿过一扇神秘的门坠落而结束。你认为门的另一边是什么，它又可能如何让这些家庭重聚？"},
                 "guidance": {"en": ["Recall the notes from Jasper and Anna about the door.", "Think about why Sarah and Qynn each wanted to find their missing family members."],
                              "zh": ["回想贾斯珀和安娜关于那扇门的留言。", "想想萨拉和昆各自为何想找到失踪的家人。"]}},
}

# ---------------------------------------------------------------
# 5. the-red-baron
# ---------------------------------------------------------------
redbaron = {
    "slug": "the-red-baron",
    "title": "The Red Baron",
    "titleZh": "红男爵",
    "level": "T",
    "genre": "Biography",
    "mainSkill": "Key Ideas and Details",
    "questions": [
        {"q": {"en": "When and where was the Red Baron born?", "zh": "“红男爵”生于何时何地？"},
         "options": [{"en": "In 1892, in Germany", "zh": "1892年，出生于德国"},
                     {"en": "In 1880, in France", "zh": "1880年，出生于法国"},
                     {"en": "In 1900, in Britain", "zh": "1900年，出生于英国"},
                     {"en": "In 1875, in Canada", "zh": "1875年，出生于加拿大"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Manfred von Richthofen was born in 1892 in Germany. His family were minor nobles, so he was sometimes called a baron.", "zh": "曼弗雷德·冯·里希特霍芬于1892年生于德国。他的家族是低级贵族，因此有时被称为男爵。"}},
        {"q": {"en": "Why did Richthofen want to join the flying service?", "zh": "里希特霍芬为什么要加入飞行队？"},
         "options": [{"en": "He was tired of the trenches and excited by pilots in the clean air", "zh": "他厌烦了战壕，又对晴空中飞行的飞行员心驰神往"},
                     {"en": "He wanted to be a cavalry officer", "zh": "他想当骑兵军官"},
                     {"en": "He was ordered to by his father", "zh": "那是他父亲下的命令"},
                     {"en": "He could not ride a horse", "zh": "因为他不会骑马"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Stuck in filthy trenches, he watched airplanes fly through clean air and wrote that joining the flying service became his 'greatest wish.'", "zh": "困在肮脏的战壕里，他看着飞机在晴空中飞行，并写道加入飞行队成了他“最大的愿望”。"}},
        {"q": {"en": "What makes a pilot an 'ace'?", "zh": "怎样才算一名“王牌飞行员（ace）”？"},
         "options": [{"en": "Shooting down five or more enemy planes", "zh": "击落五架或更多敌机"},
                     {"en": "Flying for five years", "zh": "飞行满五年"},
                     {"en": "Winning a medal", "zh": "获得一枚勋章"},
                     {"en": "Being the youngest pilot", "zh": "成为最年轻的飞行员"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "The book's 'Word Wise' says an ace is a pilot credited with shooting down five or more enemy planes. Richthofen became an ace by October 16, 1916.", "zh": "书中的“词汇角”说，王牌飞行员是指被记功击落五架或以上敌机的飞行员。里希特霍芬在1916年10月16日成为王牌。"}},
        {"q": {"en": "Who trained Richthofen, and what was special about his teaching?", "zh": "是谁训练了里希特霍芬，他的教学有什么特别？"},
         "options": [{"en": "Oswald Boelcke, who gave his men a list of eight rules", "zh": "奥斯瓦尔德·伯尔克，他给部下列了八条规则"},
                     {"en": "His father, a cavalry officer", "zh": "他的父亲，一名骑兵军官"},
                     {"en": "The British Royal Flying Corps", "zh": "英国皇家飞行队"},
                     {"en": "A school teacher", "zh": "一位学校老师"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "Richthofen joined the group led by Germany's greatest fighter pilot, Oswald Boelcke, who made a list of eight rules for combat.", "zh": "里希特霍芬加入了由德国最出色的战斗机飞行员奥斯瓦尔德·伯尔克率领的小组，伯尔克为作战列了八条规则。"}},
        {"q": {"en": "Why was Richthofen's group called the 'Flying Circus'?", "zh": "里希特霍芬的小组为什么被称为“飞行马戏团”？"},
         "options": [{"en": "He painted his plane red and his men painted theirs bright colors", "zh": "他把飞机漆成红色，部下们也把飞机漆得五彩缤纷"},
                     {"en": "They performed tricks at fairs", "zh": "他们在集市上表演特技"},
                     {"en": "They traveled with animals", "zh": "他们带着动物出行"},
                     {"en": "They wore clown costumes", "zh": "他们穿着小丑服装"}],
         "answer": 0, "skill": "Integration of Knowledge and Ideas",
         "explain": {"en": "Richthofen had his Albatros painted bright red to be seen in the sky; his men followed with bright colors, so the Allies called the colorful group the 'Flying Circus.'", "zh": "里希特霍芬把他的阿尔巴特罗斯战机漆成鲜红以便空中识别；部下们也漆上亮色，于是协约国称这个五彩的小组为“飞行马戏团”。"}},
        {"q": {"en": "What was 'Bloody April'?", "zh": "“血腥四月（Bloody April）”指的是什么？"},
         "options": [{"en": "April 1917, when Richthofen's group shot down 89 British planes", "zh": "1917年4月，里希特霍芬的小组击落了89架英国飞机"},
                     {"en": "A holiday in Germany", "zh": "德国的一个节日"},
                     {"en": "The month Richthofen was born", "zh": "里希特霍芬出生的月份"},
                     {"en": "The end of the war", "zh": "战争结束的月份"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "In April 1917 Richthofen's pilots shot down 89 planes of Britain's Royal Flying Corps; the RFC lost 245 aircraft that month, remembered as Bloody April.", "zh": "1917年4月，里希特霍芬的飞行员击落了英国皇家飞行队的89架飞机；皇家飞行队当月损失245架飞机，史称“血腥四月”。"}},
        {"q": {"en": "What was the 'Blue Max'?", "zh": "“蓝马克斯（Blue Max）”是什么？"},
         "options": [{"en": "Germany's highest military medal, awarded to Richthofen", "zh": "德国最高军事勋章，授予了里希特霍芬"},
                     {"en": "The name of his red plane", "zh": "他那架红色飞机的名字"},
                     {"en": "A type of bullet", "zh": "一种子弹"},
                     {"en": "A French city", "zh": "一座法国城市"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "With sixteen victories by January 1917, Richthofen was awarded Germany's highest military medal, the 'Blue Max,' and put in charge of his own fighter group.", "zh": "到1917年1月，里希特霍芬已取得16次胜利，获颁德国最高军事勋章“蓝马克斯”，并受命统领自己的战斗机中队。"}},
        {"q": {"en": "Which plane is the Red Baron most remembered for flying?", "zh": "“红男爵”最让人记住的是驾驶哪种飞机？"},
         "options": [{"en": "The Fokker Triplane, with three sets of wings", "zh": "福克三翼机，有三对机翼"},
                     {"en": "A hot-air balloon", "zh": "热气球"},
                     {"en": "A helicopter", "zh": "直升机"},
                     {"en": "A ship", "zh": "一艘船"}],
         "answer": 0, "skill": "Craft and Structure",
         "explain": {"en": "Returning to the front in August 1917, he traded his biplane for a slow but nimble triplane, which quickly became the aircraft he is most remembered for.", "zh": "1917年8月回到前线后，他换下双翼机，改飞虽慢却灵活的“三翼机”，这也成了他最被人记住的机型。"}},
        {"q": {"en": "How many confirmed victories did the Red Baron have?", "zh": "“红男爵”有多少次被确认的战果？"},
         "options": [{"en": "Eighty confirmed victories", "zh": "八十次被确认的战果"},
                     {"en": "Ten confirmed victories", "zh": "十次被确认的战果"},
                     {"en": "One hundred victories", "zh": "一百次战果"},
                     {"en": "Five confirmed victories", "zh": "五次被确认的战果"}],
         "answer": 0, "skill": "Key Ideas and Details",
         "explain": {"en": "On April 20, 1918, he scored his eightieth victory. With eighty confirmed victories, he was the greatest ace of World War I.", "zh": "1918年4月20日，他取得第八十次胜利。凭借八十次被确认的战果，他成了第一次世界大战中最伟大的王牌飞行员。"}},
        {"q": {"en": "Who is believed to have fired the shot that killed the Red Baron?", "zh": "据信是谁开枪打死了“红男爵”？"},
         "options": [{"en": "Uncertain — a Canadian pilot or an Australian ground gunner", "zh": "不确定——可能是加拿大飞行员，也可能是澳大利亚高射枪手"},
                     {"en": "His own brother", "zh": "他自己的兄弟"},
                     {"en": "A French general", "zh": "一位法国将军"},
                     {"en": "Oswald Boelcke", "zh": "奥斯瓦尔德·伯尔克"}],
         "answer": 0, "skill": "Author's Purpose and Perspective",
         "explain": {"en": "No one is certain who fired the bullet. Canadians thought it was Captain Arthur Brown, but many historians believe it came from an Australian gunner on the ground.", "zh": "没人能确定是谁开的枪。加拿大人认为出自亚瑟·布朗上尉，但许多历史学家相信子弹来自一名澳大利亚高射枪手。"}},
    ],
    "extended": {"prompt": {"en": "The Red Baron was a national hero to Germany but an enemy to the Allies. Was he a hero or a villain? Use evidence from the book to support your answer.", "zh": "“红男爵”在德国是民族英雄，对协约国却是敌人。他是英雄还是坏人？请用书中的证据来支持你的看法。"},
                 "guidance": {"en": ["Note that the Allies buried him with full honors and called him 'our gallant and worthy foe.'", "Consider both his skill as a pilot and the fact that war made him an enemy."],
                              "zh": ["注意协约国以全套军礼安葬他，称他为“我们英勇可敬的敌人”。", "既要考虑他作为飞行员的技艺，也要想到是战争使他成为敌人。"]}},
}

# ---------------------------------------------------------------
# Write all files
# ---------------------------------------------------------------
books = [thomas, hollow1, hollow2, hollow3, redbaron]
for b in books:
    path = os.path.join(OUT_DIR, b["slug"] + ".json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(b, f, ensure_ascii=False, indent=2)
    print("WROTE", path)

# Self-validation
for b in books:
    path = os.path.join(OUT_DIR, b["slug"] + ".json")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    assert len(data["questions"]) == 10, f"{b['slug']}: wrong question count"
    assert isinstance(data["extended"], dict), f"{b['slug']}: extended not dict"
    for q in data["questions"]:
        assert len(q["options"]) == 4, f"{b['slug']}: options != 4"
        assert isinstance(q["answer"], int) and 0 <= q["answer"] <= 3
        assert q["q"]["en"] and q["q"]["zh"]
        assert q["explain"]["en"] and q["explain"]["zh"]
        for o in q["options"]:
            assert o["en"] and o["zh"]
    assert data["extended"]["prompt"]["en"] and data["extended"]["prompt"]["zh"]
    assert data["extended"]["guidance"]["en"] and data["extended"]["guidance"]["zh"]
    assert len(data["extended"]["guidance"]["en"]) >= 1 and len(data["extended"]["guidance"]["zh"]) >= 1
    print("VALID OK", b["slug"])
print("ALL DONE")
