# -*- coding: utf-8 -*-
import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

books = []

# 1. Storm Chasers
books.append({
  "slug": "storm-chasers",
  "title": "Storm Chasers",
  "titleZh": "追风者",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"According to the book, what do MOST storm chasers do?","zh":"根据本书，大多数追风者从事什么工作？"},
     "options":[{"en":"Photograph tornadoes for money","zh":"为赚钱拍摄龙卷风"},{"en":"Are scientists and meteorologists who study the weather","zh":"是研究天气的科学家和气象学家"},{"en":"Sell tornado warnings to towns","zh":"向城镇出售龙卷风警报"},{"en":"Build tornado shelters","zh":"建造防龙卷风的避难所"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says, 'most storm chasers are scientists and meteorologists who study the weather.'","zh":"书中写道：“大多数追风者都是研究天气的科学家和气象学家。”"}},
    {"q":{"en":"In the book, what does the word 'waterspout' mean?","zh":"在本书中，“waterspout”（水龙卷）一词是什么意思？"},
     "options":[{"en":"A tornado over water","zh":"发生在水面上的龙卷风"},{"en":"A type of cloud","zh":"一种云"},{"en":"A funnel cloud on land","zh":"陆地上的漏斗云"},{"en":"Very heavy rain","zh":"非常大的雨"}],
     "answer":0,"skill":"Craft and Structure",
     "explain":{"en":"The book states, 'A tornado over water is called a waterspout.'","zh":"书中写道：“发生在水面上的龙卷风被称为水龙卷。”"}},
    {"q":{"en":"Where do more than half of Earth's tornadoes hit in the United States?","zh":"在美国，超过一半的龙卷风发生在哪个地区？"},
     "options":[{"en":"A central section called 'Tornado Alley'","zh":"被称为“龙卷风走廊”的中部地区"},{"en":"Along the East Coast only","zh":"仅沿东海岸"},{"en":"In Texas only","zh":"仅在得克萨斯州"},{"en":"Near the Great Lakes","zh":"五大湖附近"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says more than half of Earth's tornadoes hit 'the central section of the United States called Tornado Alley.'","zh":"书中说，超过一半的龙卷风袭击“美国中部被称为‘龙卷风走廊’的地区”。"}},
    {"q":{"en":"How fast can the strongest 'super tornadoes' blow?","zh":"最强的“超级龙卷风”风速可达多少？"},
     "options":[{"en":"About 160 kph (100 mph)","zh":"约每小时160公里（100英里）"},{"en":"402 to more than 482 kph (250-300 mph)","zh":"每小时402至超过482公里（250-300英里）"},{"en":"Less than 200 kph (125 mph)","zh":"低于每小时200公里（125英里）"},{"en":"About 100 kph (62 mph)","zh":"约每小时100公里（62英里）"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says the strongest tornadoes, 'sometimes called super tornadoes, have wind speeds of 402 kph to more than 482 kph.'","zh":"书中说，最强的龙卷风“有时被称为超级龙卷风，风速为每小时402至超过482公里”。"}},
    {"q":{"en":"What is a 'tornado watch' according to the glossary?","zh":"根据词汇表，“tornado watch”（龙卷风观察警报）是什么？"},
     "options":[{"en":"A warning that a tornado has been spotted","zh":"龙卷风已被发现的警告"},{"en":"An alert given when conditions are right for a tornado","zh":"当具备形成龙卷风的条件时发布的警报"},{"en":"A type of storm shelter","zh":"一种防风暴避难所"},{"en":"A forecast for rain only","zh":"仅预报下雨"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The glossary defines a tornado watch as 'alert given when conditions are right for a tornado.'","zh":"词汇表将“tornado watch”定义为“当具备形成龙卷风的条件时发布的警报”。"}},
    {"q":{"en":"Why does the author include the story of storm chaser Warren Faidley?","zh":"作者为什么要加入追风者沃伦·费德利的故事？"},
     "options":[{"en":"To show that storm chasing is easy","zh":"为了说明追风很容易"},{"en":"To give a real example of a storm chaser's life and the risks involved","zh":"给出一个关于追风者生活及其所面临风险的真实例子"},{"en":"To explain how to photograph tornadoes","zh":"为了说明如何拍摄龙卷风"},{"en":"To prove tornadoes are harmless","zh":"为了证明龙卷风无害"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The author uses Faidley's experience—sometimes going a year without seeing a tornado—to show the reality and risks of a storm chaser's job.","zh":"作者借费德利的经历（有时一整年都看不到龙卷风）来说明追风者工作的真实情况和风险。"}},
    {"q":{"en":"What does Doppler radar help meteorologists do?","zh":"多普勒雷达能帮助气象学家做什么？"},
     "options":[{"en":"Predict tornadoes exactly 7 days ahead","zh":"提前7天精确预测龙卷风"},{"en":"Track storms and give people about a 20-minute warning","zh":"追踪风暴并为人们提供约20分钟的预警"},{"en":"Build safer houses","zh":"建造更安全的房屋"},{"en":"Measure a tornado's size after it hits","zh":"在龙卷风过后测量其大小"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says meteorologists use Doppler radar to track storms and 'can give people about a 20-minute warning for a tornado.'","zh":"书中说，气象学家使用多普勒雷达追踪风暴，并“能为人们提供约20分钟的龙卷风预警”。"}},
    {"q":{"en":"The F-scale ratings for tornadoes are based on what?","zh":"龙卷风的F等级评级是基于什么？"},
     "options":[{"en":"Wind speed measured before the storm","zh":"风暴来临前测得的风速"},{"en":"How much destruction a tornado caused","zh":"龙卷风造成的破坏程度"},{"en":"The size of the funnel cloud","zh":"漏斗云的大小"},{"en":"The number of people inside","zh":"里面的人数"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The book states the F-ratings 'are based on how much destruction a tornado caused,' judged by an expert after the hit.","zh":"书中说，F等级“基于龙卷风造成的破坏程度”，由专家在袭击过后进行判断。"}},
    {"q":{"en":"According to the 'recipe for a tornado,' which conditions are needed?","zh":"根据“龙卷风的形成配方”，需要哪些条件？"},
     "options":[{"en":"Warm moist air near the ground, cool dry air above, and a cold air mass colliding with a warm one","zh":"近地面温暖潮湿的空气、上方凉爽干燥的空气，以及冷气团与暖气团相撞"},{"en":"High winds, lightning, and hail","zh":"大风、闪电和冰雹"},{"en":"Snow, ice, and fog","zh":"雪、冰和雾"},{"en":"Sunshine, low pressure, and rain","zh":"阳光、低气压和雨"}],
     "answer":0,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The recipe lists warm moist air near the ground, cool dry air above, and a cold air mass colliding with a warm air mass.","zh":"配方列出了：近地面温暖潮湿的空气、上方凉爽干燥的空气，以及冷气团与暖气团相撞。"}},
    {"q":{"en":"What is the main message of the book?","zh":"本书的主要信息是什麼？"},
     "options":[{"en":"Storms are fun to watch","zh":"看风暴很有趣"},{"en":"Storm chasers study tornadoes to better predict them and save lives","zh":"追风者研究龙卷风，以更好地预测它们并挽救生命"},{"en":"Everyone should become a meteorologist","zh":"每个人都应该成为气象学家"},{"en":"Tornadoes only happen in Texas","zh":"龙卷风只发生在得克萨斯州"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The introduction says storm chasers 'collect information that will help them better predict tornadoes and save lives.'","zh":"引言说，追风者“收集信息，帮助他们更好地预测龙卷风并挽救生命。”"}}
  ],
  "extended":{
    "prompt":{"en":"Imagine you are a storm chaser. Write a short paragraph describing what you would do during a tornado warning and why safety matters.","zh":"想象你是一名追风者。写一小段话，描述在龙卷风警报发布时你会怎么做，以及为什么安全很重要。"},
    "guidance":{"en":["Describe the steps you would take to stay safe (get indoors, low floor, away from windows).","Explain why collecting data helps scientists protect people."],
               "zh":["描述你会采取哪些安全措施（进入室内、待在较低楼层、远离窗户）。","解释为什么收集数据能帮助科学家保护人们。"]}
  }
})

# 2. Speed
books.append({
  "slug": "speed",
  "title": "Speed",
  "titleZh": "速度",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"What is the fastest living thing on land?","zh":"陆地上最快的生物是什么？"},
     "options":[{"en":"A cheetah","zh":"猎豹"},{"en":"A horse","zh":"马"},{"en":"A peregrine falcon","zh":"游隼"},{"en":"A sailfish","zh":"旗鱼"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the cheetah, which runs up to 113 kph, 'is the fastest living thing on land.'","zh":"书中说，猎豹奔跑速度可达每小时113公里，是“陆地上最快的生物”。"}},
    {"q":{"en":"In the book, what does 'hydroplaning' mean for a boat?","zh":"在本书中，船的“hydroplaning”（滑水）是什么意思？"},
     "options":[{"en":"A boat sinking","zh":"船下沉"},{"en":"A boat skimming over the surface and barely touching the water","zh":"船贴着水面滑行、几乎不接触水"},{"en":"A plane landing on water","zh":"飞机在水面降落"},{"en":"Sailing against the wind","zh":"逆风航行"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The book explains hydroplaning means modern racing boats 'barely touch the water as they skim over the surface.'","zh":"书中解释，滑水是指现代赛艇“贴着水面滑行，几乎不接触水”。"}},
    {"q":{"en":"Which of these living things is the fastest?","zh":"以下哪种生物速度最快？"},
     "options":[{"en":"A cheetah","zh":"猎豹"},{"en":"A sailfish","zh":"旗鱼"},{"en":"A peregrine falcon","zh":"游隼"},{"en":"A human","zh":"人类"}],
     "answer":2,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says the peregrine falcon 'reaches speeds of 435 kph' diving—faster than cheetahs (113 kph) and sailfish (113 kph).","zh":"书中说游隼俯冲时“速度可达每小时435公里”，快于猎豹（113公里）和旗鱼（113公里）。"}},
    {"q":{"en":"What was the first recognized land-speed record for an automobile in 1898?","zh":"1898年公认的第一项汽车陆地速度纪录是多少？"},
     "options":[{"en":"63.13 kph (39.24 mph) by an electric car","zh":"电动汽车创造的每小时63.13公里（39.24英里）"},{"en":"1,228 kph (763 mph)","zh":"每小时1228公里（763英里）"},{"en":"320 kph (200 mph)","zh":"每小时320公里（200英里）"},{"en":"40 kph (25 mph)","zh":"每小时40公里（25英里）"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the first recognized automobile land-speed record, set in 1898, was '63.13 kph' by an electric motor.","zh":"书中说，1898年创造的第一项公认的汽车陆地速度纪录是由电动机驱动的“每小时63.13公里”。"}},
    {"q":{"en":"Why does the author mention that light moves at 299,338 km per second?","zh":"作者为什么要提到光每秒移动299,338公里？"},
     "options":[{"en":"To show that light is slow","zh":"为了说明光很慢"},{"en":"To give an example of something measured in very large units over a very short time","zh":"为了举例说明某些事物使用很大的距离单位和很短的时间单位来计量"},{"en":"To explain how a car works","zh":"为了解释汽车如何运作"},{"en":"To describe a rocket","zh":"为了描述火箭"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The author uses light as the fastest thing in the universe to show that faster objects are measured in larger distance units over shorter time.","zh":"作者以光作为宇宙中速度最快的事物，说明越快的物体越用更大的距离单位和更短的时间单位来计量。"}},
    {"q":{"en":"Who was the first human to go faster than the speed of sound on land?","zh":"谁是第一个在陆地上超过音速的人？"},
     "options":[{"en":"Charles Murphy","zh":"查尔斯·墨菲"},{"en":"Andy Green in the Thrust SSC","zh":"驾驶Thrust SSC的安迪·格林"},{"en":"Malcolm Campbell","zh":"马尔科姆·坎贝尔"},{"en":"A bullet-train driver","zh":"子弹头列车驾驶员"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says in October 1997 Andy Green 'became the first human to go faster than the speed of sound in a land vehicle' (1,228 kph).","zh":"书中说，1997年10月，安迪·格林“成为第一个在陆地车辆上超过音速的人”（每小时1228公里）。"}},
    {"q":{"en":"Why did early bicycles have a problem going fast?","zh":"早期的自行车为什么难以提速？"},
     "options":[{"en":"They were too heavy","zh":"它们太重了"},{"en":"Air resistance pushed back harder as speed increased","zh":"速度越快，空气阻力推得越厉害"},{"en":"They had no wheels","zh":"它们没有轮子"},{"en":"The riders got too tired","zh":"骑行者太累了"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book explains, 'As we ride faster, the air seems to push back harder'—this air resistance slows cyclists.","zh":"书中解释：“我们骑得越快，空气似乎推得越厉害”——这种空气阻力使骑行者变慢。"}},
    {"q":{"en":"What is the main topic of the book?","zh":"本书的主题是什么？"},
     "options":[{"en":"How to build a rocket","zh":"如何建造火箭"},{"en":"Speed—how it is measured and how different things move fast","zh":"速度——它如何被衡量，以及不同事物如何快速移动"},{"en":"The history of trains","zh":"火车的历史"},{"en":"Why cheetahs are slow","zh":"为什么猎豹很慢"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The book compares how speed is measured and how living things, vehicles, and even light move at different speeds.","zh":"本书比较了速度如何被衡量，以及生物、交通工具甚至光以不同速度运动。"}},
    {"q":{"en":"About how fast can a magnetic 'bullet train' travel?","zh":"磁悬浮“子弹头列车”大约能跑多快？"},
     "options":[{"en":"Nearly 320 kph (200 mph)","zh":"接近每小时320公里（200英里）"},{"en":"65 kph (40 mph)","zh":"每小时65公里（40英里）"},{"en":"Over 800 kph right now","zh":"目前已经超过每小时800公里"},{"en":"45,062 kph (28,000 mph)","zh":"每小时45,062公里（28,000英里）"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says modern bullet trains 'now travel at speeds of nearly 320 kilometers per hour.'","zh":"书中说，现代子弹头列车“目前的时速接近320公里”。"}},
    {"q":{"en":"What does the author say about the future of human speed?","zh":"关于人类速度的未来，作者说了什么？"},
     "options":[{"en":"Cheetahs will get faster","zh":"猎豹会变得更快"},{"en":"Humans will keep finding new ways to go faster, even toward the speed of light","zh":"人类会不断找到提速的新方法，甚至接近光速"},{"en":"Speed records are finished","zh":"速度纪录已经到头了"},{"en":"Rockets will be banned","zh":"火箭将被禁止"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The conclusion says humans 'will continue to find ways to go faster' and one day may travel at the speed of light.","zh":"结论说，人类“将继续找到提速的方法”，有朝一日或许能以光速旅行。"}}
  ],
  "extended":{
    "prompt":{"en":"Choose one vehicle from the book (bicycle, boat, train, automobile, or aircraft) and explain how people made it go faster over time.","zh":"从书中选择一种交通工具（自行车、船、火车、汽车或飞机），并说明人们是如何让它随着时间变得越来越快的。"},
    "guidance":{"en":["Name the vehicle and an early speed mentioned.","Describe one invention or change that increased its speed."],
               "zh":["说出这种交通工具以及书中提到的一个早期速度。","描述一项使其提速的发明或改变。"]}
  }
})

# 3. Skydiving
books.append({
  "slug": "skydiving",
  "title": "Skydiving",
  "titleZh": "跳伞",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"How old was Bob Gates when he made his first jump?","zh":"鲍勃·盖茨第一次跳伞时几岁？"},
     "options":[{"en":"10","zh":"10岁"},{"en":"13","zh":"13岁"},{"en":"18","zh":"18岁"},{"en":"21","zh":"21岁"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Bob says, 'I was 13' when he made his first jump.","zh":"鲍勃说，他第一次跳伞时“13岁”。"}},
    {"q":{"en":"What does 'the arch' mean in skydiving?","zh":"在跳伞中，“the arch”（弓身）是什么意思？"},
     "options":[{"en":"A type of parachute","zh":"一种降落伞"},{"en":"Spreading out and pushing your hips forward to stay stable","zh":"张开身体并向前顶胯以保持稳定"},{"en":"A way to land","zh":"一种着陆方式"},{"en":"A kind of jump","zh":"一种跳跃方式"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines arch as 'a skydiving position in which a person falls stomach-down with the hips thrust forward.'","zh":"词汇表将arch定义为“跳伞者面朝下、向前顶胯下落的姿势”。"}},
    {"q":{"en":"Why can't skydivers jump higher than 13,000 feet?","zh":"为什么跳伞者不能从高于13,000英尺的高度跳下？"},
     "options":[{"en":"The plane cannot fly that high","zh":"飞机飞不了那么高"},{"en":"There is not enough oxygen in the air","zh":"空气中的氧气不足"},{"en":"It is against the law","zh":"这违法"},{"en":"The parachute will not open","zh":"降落伞打不开"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Bob says, 'You can't go higher than 13,000 feet because there's not enough oxygen in the air.'","zh":"鲍勃说：“你不能高于13,000英尺，因为空气中的氧气不足。”"}},
    {"q":{"en":"What happens if a skydiver does NOT do the arch?","zh":"如果跳伞者不做出“弓身”动作会怎样？"},
     "options":[{"en":"They fall faster","zh":"他们下落得更快"},{"en":"They can flip and get tangled in the lines","zh":"他们会翻滚并被绳索缠住"},{"en":"The chute opens immediately","zh":"降落伞立刻打开"},{"en":"Nothing changes","zh":"没有任何变化"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"Bob says, 'You can flip. If you're flipping when the chute's opening, you can get tangled in the lines.'","zh":"鲍勃说：“你会翻滚。如果在开伞时正在翻滚，就会被绳索缠住。”"}},
    {"q":{"en":"How long does a free fall from 13,000 feet last?","zh":"从13,000英尺高度自由落体大约持续多久？"},
     "options":[{"en":"About 10 minutes","zh":"约10分钟"},{"en":"Just about a whole minute","zh":"大约整整一分钟"},{"en":"5 seconds","zh":"5秒"},{"en":"2 hours","zh":"2小时"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Bob says a free fall from 13,000 feet lasts 'Just a whole minute.'","zh":"鲍勃说，从13,000英尺自由落体“大约整整一分钟”。"}},
    {"q":{"en":"Why does Bob Gates keep skydiving?","zh":"鲍勃·盖茨为什么一直坚持跳伞？"},
     "options":[{"en":"He has to for his job","zh":"这是他的工作要求"},{"en":"He loves the adrenaline rush","zh":"他喜欢那种肾上腺素飙升的刺激感"},{"en":"His children make him","zh":"他的孩子们逼他"},{"en":"It is free","zh":"这是免费的"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"Bob says, 'We skydivers love the feeling of extreme excitement—the adrenaline rush—when we jump.'","zh":"鲍勃说：“我们跳伞者喜欢那种极度兴奋的感觉——跳伞时的肾上腺素飙升。”"}},
    {"q":{"en":"What are 'toggles' on a parachute?","zh":"降落伞上的“toggles”是什么？"},
     "options":[{"en":"The reserve parachute","zh":"备用降落伞"},{"en":"Ropes on either side used to steer the parachute","zh":"两侧用来操控降落伞的绳索"},{"en":"The altimeter","zh":"高度计"},{"en":"The helmet","zh":"头盔"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines toggle ropes as 'ropes on either side of a parachute that allow the skydiver to steer.'","zh":"词汇表将toggles定义为“降落伞两侧的绳索，供跳伞者操控方向”。"}},
    {"q":{"en":"According to the trivia, when were parachutes first used to jump from airplanes?","zh":"根据书中的小知识，降落伞最早是在什么时候被用于从飞机上跳下的？"},
     "options":[{"en":"900 years ago in China","zh":"900年前在中国"},{"en":"In the early 1900s","zh":"20世纪初"},{"en":"In 1797","zh":"1797年"},{"en":"After World War II","zh":"二战之后"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The trivia says, 'Parachutes were first used to jump from airplanes in the early 1900s.'","zh":"小知识说：“降落伞最早在20世纪初被用于从飞机上跳下。”"}},
    {"q":{"en":"How much does skydiving training cost?","zh":"跳伞训练的费用是多少？"},
     "options":[{"en":"$1,000 to $1,500","zh":"1,000至1,500美元"},{"en":"Free","zh":"免费"},{"en":"$2,000 to $4,000","zh":"2,000至4,000美元"},{"en":"$20","zh":"20美元"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"Bob says a skydiver spends '$1,000 to $1,500' for the training course (the parachute itself costs $2,000-$4,000).","zh":"鲍勃说，跳伞者要在训练课程上花费“1,000至1,500美元”（降落伞本身需2,000至4,000美元）。"}},
    {"q":{"en":"What lesson does the book mainly share?","zh":"本书主要传达了什么道理？"},
     "options":[{"en":"Skydiving is dangerous and should be avoided","zh":"跳伞很危险，应该避免"},{"en":"With good training and trust in equipment, skydivers can handle hard situations and enjoy the thrill","zh":"凭借良好的训练和对装备的信任，跳伞者能应对困难局面并享受刺激"},{"en":"Everyone must go skydiving","zh":"每个人都必須跳伞"},{"en":"Planes are safer than parachutes","zh":"飞机比降落伞更安全"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book notes, 'Good training and faith in the equipment will allow a skydiver to handle almost any difficult situation.'","zh":"书中指出：“良好的训练和对装备的信任，能让跳伞者应对几乎任何困难局面。”"}}
  ],
  "extended":{
    "prompt":{"en":"Pretend you interviewed a skydiver like Bob Gates. Write three questions you would ask and what you hope to learn.","zh":"假设你要采访一位像鲍勃·盖茨这样的跳伞者。写出你想问的三个问题，以及你希望从中了解到什么。"},
    "guidance":{"en":["Think about safety, training, and feelings.","Explain why their answers would be interesting."],
               "zh":["思考安全、训练和感受方面的问题。","解释为什么他们的回答会很有趣。"]}
  }
})

# 4. Ships and Boats
books.append({
  "slug": "ships-and-boats",
  "title": "Ships and Boats",
  "titleZh": "船与舰艇",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"What were the earliest boats made from?","zh":"最早的船是用什么做的？"},
     "options":[{"en":"Metal","zh":"金属"},{"en":"Single wooden logs carved out","zh":"挖空的原木"},{"en":"Plastic","zh":"塑料"},{"en":"Stone","zh":"石头"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the original boats 'were carved from single wooden logs'—dugout canoes dating back to the Stone Age.","zh":"书中说，最早的船“由整根原木挖凿而成”——即可追溯到石器时代的独木舟。"}},
    {"q":{"en":"A 'catamaran' is...","zh":"“catamaran”（双体船）是……"},
     "options":[{"en":"A ship with one hull","zh":"单船体的船"},{"en":"A boat with two hulls","zh":"有两个船体的船"},{"en":"A type of sail","zh":"一种帆"},{"en":"An oar","zh":"一支桨"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines a catamaran as 'a boat with two hulls.'","zh":"词汇表将catamaran定义为“有两个船体的船”。"}},
    {"q":{"en":"How were Viking longships like the older galleys?","zh":"维京长船与更早的桨帆船有什么相似之处？"},
     "options":[{"en":"Both were made of stone","zh":"两者都用石头制成"},{"en":"Both used many rowers and also had sails","zh":"两者都使用众多划桨手，并且也装有帆"},{"en":"Both were used only for trade","zh":"两者都只用于贸易"},{"en":"Neither had sails","zh":"两者都没有帆"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"Like galleys, longships 'had sails in addition to their oars' and carried many oarsmen.","zh":"和桨帆船一样，长船“除了桨之外还有帆”，并载有众多划桨手。"}},
    {"q":{"en":"What happened to the Titanic?","zh":"泰坦尼克号发生了什么？"},
     "options":[{"en":"It crossed the Atlantic fastest","zh":"它最快横渡大西洋"},{"en":"It sank in the North Atlantic after hitting an iceberg in 1912","zh":"它于1912年撞上冰山后沉没于北大西洋"},{"en":"It is still sailing","zh":"它仍在航行"},{"en":"It was a pirate ship","zh":"它是一艘海盗船"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the Titanic 'sank in the North Atlantic Ocean after striking an iceberg in 1912.'","zh":"书中说，泰坦尼克号“于1912年撞上冰山后沉没于北大西洋”。"}},
    {"q":{"en":"Why does the author say ships and boats 'helped to shape history'?","zh":"作者为什么说船“帮助塑造了历史”？"},
     "options":[{"en":"They were used only for fun","zh":"它们只用于娱乐"},{"en":"They led explorers to new lands and carried goods, people, and ideas around the world","zh":"它们带领探险家到达新大陆，并把货物、人和思想带到世界各地"},{"en":"They replaced all roads","zh":"它们取代了所有道路"},{"en":"They were the first airplanes","zh":"它们是最早的飞机"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The introduction says boats 'helped to shape history, leading explorers to new lands and carrying goods, people, and ideas around the world.'","zh":"引言说，船“帮助塑造了历史，带领探险家到达新大陆，并把货物、人和思想带到世界各地”。"}},
    {"q":{"en":"What is the job of a propeller?","zh":"螺旋桨的作用是什么？"},
     "options":[{"en":"To catch the wind","zh":"捕捉风"},{"en":"Rotating blades connected to an engine that push a boat through the water","zh":"连接引擎、推动船前进的旋转叶片"},{"en":"To steer the ship","zh":"操控船的方向"},{"en":"To hold the sails","zh":"固定船帆"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The glossary defines propellers as 'rotating blades connected to an engine that push a boat through the water.'","zh":"词汇表将螺旋桨定义为“连接引擎、推动船在水中前进的旋转叶片”。"}},
    {"q":{"en":"Which special boat helps put out fires on other ships?","zh":"哪种特殊船只帮助扑灭其他船上的火？"},
     "options":[{"en":"A ferryboat","zh":"渡轮"},{"en":"A fireboat","zh":"消防船"},{"en":"A tugboat","zh":"拖船"},{"en":"A submarine","zh":"潜艇"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says, 'Fireboats help put out fires on other ships.'","zh":"书中说：“消防船帮助扑灭其他船上的火。”"}},
    {"q":{"en":"What is the main idea of the book?","zh":"本书的主旨是什么？"},
     "options":[{"en":"Only modern ships matter","zh":"只有现代船只才重要"},{"en":"Boats and ships have changed over time but still share features with the earliest designs","zh":"船随着时间演变，但仍与最早的设计有共同特征"},{"en":"Pirates were the best sailors","zh":"海盗是最棒的航海者"},{"en":"The Titanic was unsinkable","zh":"泰坦尼克号是永不沉没的"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The introduction notes boats 'still share many features with the earliest designs' even though they have changed a lot.","zh":"引言指出，尽管船已发生很大变化，但仍“与最早的设计有许多共同特征”。"}},
    {"q":{"en":"About how long is the largest oil tanker in the world?","zh":"世界上最大的油轮大约有多长？"},
     "options":[{"en":"Over 457 meters (1,500 ft)","zh":"超过457米（1,500英尺）"},{"en":"90 meters (300 ft)","zh":"90米（300英尺）"},{"en":"304 meters (1,000 ft)","zh":"304米（1,000英尺）"},{"en":"28 meters (90 ft)","zh":"28米（90英尺）"}],
     "answer":0,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the largest oil tanker is 'over 457.2 meters (1,500 ft) long—longer than the Empire State Building is tall.'","zh":"书中说，最大的油轮“超过457.2米（1,500英尺）长——比帝国大厦还高”。"}},
    {"q":{"en":"The book is written mainly to...","zh":"本书主要为了……"},
     "options":[{"en":"Teach readers about the history and many types of ships and boats","zh":"向读者介绍船的历史和各种类型"},{"en":"Sell boats","zh":"推销船"},{"en":"Tell a story about pirates","zh":"讲述一个海盗故事"},{"en":"Explain how to swim","zh":"解释如何游泳"}],
     "answer":0,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book surveys early boats, sailing ships, steamships, modern ships, and special ships to inform readers.","zh":"本书介绍了早期船只、帆船、蒸汽船、现代船只和特殊船只，目的是向读者普及知识。"}}
  ],
  "extended":{
    "prompt":{"en":"Compare an early boat (like a dugout canoe) with a modern ship. What changed, and what stayed the same?","zh":"比较早期的船（如独木舟）与现代的船。什么改变了，什么保持不变？"},
    "guidance":{"en":["Mention one old material (logs, bark, skins) and one modern feature (engines, metal).","Note that paddles, oars, or sails are still used on smaller boats."],
               "zh":["提到一种古老材料（原木、树皮、兽皮）和一项现代特征（引擎、金属）。","指出小船仍然使用桨、橹或帆。"]}
  }
})

# 5. September 11 Always Remember
books.append({
  "slug": "september-11-always-remember",
  "title": "September 11 Always Remember",
  "titleZh": "9月11日：永远铭记",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"On September 11, 2001, how many planes were hijacked?","zh":"在2001年9月11日，共有多少架飞机被劫持？"},
     "options":[{"en":"Two","zh":"两架"},{"en":"Three","zh":"三架"},{"en":"Four","zh":"四架"},{"en":"Five","zh":"五架"}],
     "answer":2,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says, 'a group of terrorists hijacked four planes on the East Coast.'","zh":"书中说：“一群恐怖分子在东海岸劫持了四架飞机。”"}},
    {"q":{"en":"Where did the fourth plane crash?","zh":"第四架飞机坠毁在哪里？"},
     "options":[{"en":"Into the Pentagon","zh":"撞入五角大楼"},{"en":"Into the World Trade Center","zh":"撞入世贸中心"},{"en":"In a field in Pennsylvania","zh":"宾夕法尼亚州的一片田野"},{"en":"In New York City","zh":"纽约市"}],
     "answer":2,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says people on board stopped the fourth plane, and 'That plane crashed in a field in Pennsylvania.'","zh":"书中说，机上乘客阻止了第四架飞机，它“坠毁在宾夕法尼亚州的一片田野”。"}},
    {"q":{"en":"The word 'hijacked' means...","zh":"“hijacked”（劫持）一词的意思是……"},
     "options":[{"en":"To repair a vehicle","zh":"修理交通工具"},{"en":"To seize control of a vehicle by outside force","zh":"由外力夺取对交通工具的控制权"},{"en":"To fly a plane","zh":"驾驶飞机"},{"en":"To build a memorial","zh":"建造纪念碑"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines hijacked as 'seized control of a vehicle by outside force.'","zh":"词汇表将hijacked定义为“由外力夺取对交通工具的控制权”。"}},
    {"q":{"en":"Why did children in Hawaii make leis (flower necklaces)?","zh":"夏威夷的孩子们为什么要制作花环（鲜花项链）？"},
     "options":[{"en":"For a birthday party","zh":"为了生日聚会"},{"en":"To send messages of hope and support to survivors and rescue workers","zh":"向幸存者和救援人员传递希望与支持的信息"},{"en":"To sell them","zh":"用来售卖"},{"en":"To wear at school","zh":"在学校佩戴"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says children in Hawaii made leis 'with messages written on them' and sent them to survivors and rescue workers at all three sites.","zh":"书中说，夏威夷的孩子们制作了“写有信息的花环”，并寄给三个地点的幸存者和救援人员。"}},
    {"q":{"en":"How many names are carved around the pools at the New York memorial?","zh":"纽约纪念广场的水池周围刻有多少个名字？"},
     "options":[{"en":"184","zh":"184个"},{"en":"40","zh":"40个"},{"en":"2,983","zh":"2,983个"},{"en":"63","zh":"63个"}],
     "answer":2,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says 2,983 names are carved—victims of the three attacks plus the 1993 World Trade Center attack.","zh":"书中说刻有2,983个名字——包括三次袭击的遇难者以及1993年世贸中心袭击的遇难者。"}},
    {"q":{"en":"What is the author's main purpose in writing this book?","zh":"作者写这本书的主要目的是什么？"},
     "options":[{"en":"To teach about the attacks and how people remember and honor the victims","zh":"介绍袭击事件，以及人们如何纪念和缅怀遇难者"},{"en":"To argue against building memorials","zh":"反对建造纪念碑"},{"en":"To describe New York architecture","zh":"描述纽约的建筑"},{"en":"To explain how airplanes work","zh":"解释飞机如何运作"}],
     "answer":0,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book describes the attacks, the heroes, and the many memorials created so people will 'never forget.'","zh":"本书描述了袭击、英雄人物，以及众多纪念碑，目的是让人们“永不遗忘”。"}},
    {"q":{"en":"What does the word 'memorial' mean as used in this book?","zh":"在本书中，“memorial”（纪念碑/纪念物）一词是什么意思？"},
     "options":[{"en":"A type of airplane","zh":"一种飞机"},{"en":"Something that represents the memory of a person, place, thing, or event","zh":"代表对某个人、地方、事物或事件的记忆的东西"},{"en":"A kind of flower","zh":"一种花"},{"en":"A government building","zh":"政府大楼"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines a memorial as 'something that represents the memory of a person, place, thing, or event.'","zh":"词汇表将memorial定义为“代表对某个人、地方、事物或事件的记忆的东西”。"}},
    {"q":{"en":"How is the Pentagon memorial different from the Pennsylvania memorial?","zh":"五角大楼纪念碑与宾夕法尼亚纪念碑有何不同？"},
     "options":[{"en":"The Pentagon has 184 benches with victims' names; Pennsylvania has a marble wall of 40 pieces with names","zh":"五角大楼有184张刻有遇难者名字的长椅；宾夕法尼亚有一面由40块大理石组成的刻名墙"},{"en":"They are exactly the same","zh":"两者完全一样"},{"en":"Pennsylvania has 184 benches","zh":"宾夕法尼亚有184张长椅"},{"en":"The Pentagon has a wall of 40 marble pieces","zh":"五角大楼有一面由40块大理石组成的墙"}],
     "answer":0,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says the Pentagon has 184 benches (one per victim), while Pennsylvania's wall has 40 marble pieces (one per passenger).","zh":"书中说五角大楼有184张长椅（每位遇难者一张），而宾夕法尼亚的墙由40块大理石组成（每位乘客一块）。"}},
    {"q":{"en":"On what date did the New York City memorial open?","zh":"纽约市的纪念碑是在哪一天开放的？"},
     "options":[{"en":"September 11, 2001","zh":"2001年9月11日"},{"en":"September 11, 2011","zh":"2011年9月11日"},{"en":"September 11, 2008","zh":"2008年9月11日"},{"en":"February 26, 1993","zh":"1993年2月26日"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the memorial 'opened on September 11, 2011' after nearly seven years of building.","zh":"书中说，该纪念碑在建造近七年后“于2011年9月11日开放”。"}},
    {"q":{"en":"What does the author say about remembering?","zh":"关于铭记，作者说了什么？"},
     "options":[{"en":"We should forget to move on","zh":"我们应该忘记以继续前进"},{"en":"It is very important we never forget what happened and the heroes","zh":"我们永远不应忘记所发生的事以及那些英雄，这非常重要"},{"en":"Only Americans should remember","zh":"只有美国人应该铭记"},{"en":"Memorials are a waste","zh":"纪念碑是浪费"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book says, 'It is very important that we never forget what happened, the people who died, and the people who became heroes.'","zh":"书中说：“我们永远不应忘记所发生的事、逝去的人，以及那些成为英雄的人，这一点非常重要。”"}}
  ],
  "extended":{
    "prompt":{"en":"The book shows many ways people remember September 11. Design your own memorial and explain what it would represent.","zh":"书中展示了人们纪念9月11日的多种方式。设计你自己的纪念碑，并说明它代表什么。"},
    "guidance":{"en":["Describe what your memorial looks like.","Explain whose memory it honors and why."],
               "zh":["描述你的纪念碑外观。","解释它纪念的是谁，以及原因。"]}
  }
})

# 6. Seeds and Sunflowers
books.append({
  "slug": "seeds-and-sunflowers",
  "title": "Seeds and Sunflowers",
  "titleZh": "种子与向日葵",
  "level": "R",
  "genre": "Fiction",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"What does Mike want to buy?","zh":"迈克想买什么？"},
     "options":[{"en":"A bicycle","zh":"一辆自行车"},{"en":"A Super Spy kit","zh":"一个超级间谍套装"},{"en":"Sunflower seeds","zh":"葵花籽"},{"en":"A farmers' market","zh":"一个农贸市场"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Mike is 'trying to pull together sufficient funds to buy a Super Spy kit' (a friend offered his for $25).","zh":"迈克“正努力凑足钱买一个超级间谍套装”（一位朋友愿以25美元卖给他）。"}},
    {"q":{"en":"In the story, 'organic' crops are grown...","zh":"在故事中，“organic”（有机）作物是……种植的。"},
     "options":[{"en":"With chemicals","zh":"使用化学品"},{"en":"Without chemicals or artificial products","zh":"不使用化学品或人工制品"},{"en":"In water","zh":"在水中"},{"en":"By machines","zh":"由机器"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines organic as 'grown and produced without chemicals or artificial products.'","zh":"词汇表将organic定义为“不使用化学品或人工制品种植和生产的”。"}},
    {"q":{"en":"Why didn't Mike's first seeds grow into plants?","zh":"为什么迈克最初种的种子没有长成植物？"},
     "options":[{"en":"He planted them too deep","zh":"他种得太深"},{"en":"He planted roasted, salted snack seeds instead of gardening seeds","zh":"他种下的是烤过并加盐的零食种子，而非园艺种子"},{"en":"There was no sun","zh":"没有阳光"},{"en":"Squirrels ate them","zh":"松鼠吃了它们"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Mrs. McCarthy points out Mike's snacks were 'roasted and salted'—he planted the wrong kind of seeds.","zh":"麦卡锡太太指出，迈克的零食是“烤过并加盐的”——他种错了种子种类。"}},
    {"q":{"en":"What does Aster mean when she says 'they're sunflowers, Mike'?","zh":"当艾斯特说“它们是向日葵啊，迈克”时，她的意思是什么？"},
     "options":[{"en":"Sunflowers should be planted in a sunny spot","zh":"向日葵应该种在阳光充足的地方"},{"en":"Sunflowers are expensive","zh":"向日葵很贵"},{"en":"Sunflowers are red","zh":"向日葵是红色的"},{"en":"Sunflowers need only water","zh":"向日葵只需要水"}],
     "answer":0,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"Aster first told Mike his spot was 'too shady'; sunflowers need sun, so she reminds him they are sunflowers.","zh":"艾斯特先提醒迈克那个位置“太阴凉”；向日葵需要阳光，所以她提醒他这是向日葵。"}},
    {"q":{"en":"How tall were the sunflower plants by August?","zh":"到八月时，向日葵植株有多高？"},
     "options":[{"en":"Two feet","zh":"两英尺"},{"en":"Seven feet","zh":"七英尺"},{"en":"Ten feet","zh":"十英尺"},{"en":"One foot","zh":"一英尺"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says, 'By August, the plants were seven feet tall.'","zh":"书中说：“到八月，植株已有七英尺高。”"}},
    {"q":{"en":"Whose experience does the book suggest was more valuable?","zh":"本书认为谁的经历更有价值？"},
     "options":[{"en":"Mike's, because he made money","zh":"迈克的，因为他赚到了钱"},{"en":"Aster's, because her photos captured the whole experience and she understood its joy","zh":"艾斯特的，因为她的照片记录了整个经历，并且她理解了其中的乐趣"},{"en":"Neither","zh":"都不是"},{"en":"Their mother's","zh":"他们母亲的"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The focus question asks whose experience was more valuable; Aster's photos 'chronicled the sunflowers from start to finish' and she gave Mike seeds to thank him.","zh":"焦点问题问谁的经历更有价值；艾斯特的照片“从头到尾记录了向日葵”，并且她送种子给迈克以表达感谢。"}},
    {"q":{"en":"From whose point of view is the story told?","zh":"这个故事是从谁的视角叙述的？"},
     "options":[{"en":"First person from Mike","zh":"迈克的第一人称"},{"en":"A third-person narrator","zh":"第三人称叙述者"},{"en":"Aster","zh":"艾斯特"},{"en":"Mrs. McCarthy","zh":"麦卡锡太太"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The story uses a third-person narrator (e.g., 'Mike announced,' 'Aster smiled'), not a character's own voice.","zh":"故事采用第三人称叙述者（如“迈克宣布”“艾斯特微笑”），而非以角色自己的口吻。"}},
    {"q":{"en":"How were Mike's and Aster's approaches different?","zh":"迈克和艾斯特的方式有何不同？"},
     "options":[{"en":"Mike focused on making money; Aster focused on enjoying and recording the experience","zh":"迈克关注赚钱；艾斯特关注享受并记录这段经历"},{"en":"Both wanted money","zh":"两人都想要钱"},{"en":"Both ignored the plants","zh":"两人都不理会向日葵"},{"en":"Aster planted the seeds","zh":"是艾斯特种下了种子"}],
     "answer":0,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"Mike wanted to sell seeds for a kit; Aster pulled weeds, took photos, and later gifted seeds to capture the memory.","zh":"迈克想卖种子买套装；艾斯特除草、拍照，并后来赠送种子以留存记忆。"}},
    {"q":{"en":"What did Aster give Mike on the first day of autumn?","zh":"在初秋的第一天，艾斯特给了迈克什么？"},
     "options":[{"en":"A scarecrow","zh":"一个稻草人"},{"en":"A bag of roasted, salted seeds","zh":"一袋烤过并加盐的种子"},{"en":"A camera","zh":"一台相机"},{"en":"A Super Spy kit","zh":"一个超级间谍套装"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Mike 'woke to a bag of sunflower seeds on his pillow—the roasted, salted kind,' and Aster says, 'They came from me.'","zh":"迈克“醒来发现枕边有一袋葵花籽——就是烤过并加盐的那种”，艾斯特说：“是我给的。”"}},
    {"q":{"en":"What is a main message of the story?","zh":"这个故事的主要寓意是什么？"},
     "options":[{"en":"Gardening is easy","zh":"园艺很容易"},{"en":"The experience and memories of growing something can be more valuable than the money earned","zh":"种植某物的经历和记忆，可能比赚到的钱更有价值"},{"en":"Always plant in the shade","zh":"总是在阴凉处种植"},{"en":"Birds are harmful","zh":"鸟是有害的"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"Mike ends up valuing Aster's photo record of the sunflowers more than the few seeds he could sell.","zh":"迈克最终比视卖种子赚的钱更看重艾斯特对向日葵的影像记录。"}}
  ],
  "extended":{
    "prompt":{"en":"Whose experience was more valuable—Mike's or Aster's? Write a paragraph explaining your opinion with details from the story.","zh":"谁的经历更有价值——迈克还是艾斯特？写一段话，结合故事中的细节说明你的观点。"},
    "guidance":{"en":["State whose experience you think mattered more.","Use a detail, such as the photos or the bag of seeds, to support your idea."],
               "zh":["说明你认为谁的经历更重要。","用故事中的细节（如照片或那袋种子）来支持你的观点。"]}
  }
})

# 7. Sea Turtles
books.append({
  "slug": "sea-turtles",
  "title": "Sea Turtles",
  "titleZh": "海龟",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"How long have sea turtles roamed the oceans?","zh":"海龟在海洋中遨游了多久？"},
     "options":[{"en":"50 million years","zh":"5000万年"},{"en":"At least 150 million years","zh":"至少1.5亿年"},{"en":"1,000 years","zh":"1000年"},{"en":"Since dinosaurs died out","zh":"自恐龙灭绝以来"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says sea turtles 'have roamed the oceans for at least 150 million years.'","zh":"书中说，海龟“在海洋中遨游了至少1.5亿年”。"}},
    {"q":{"en":"What is the 'plastron'?","zh":"“plastron”（腹甲）是什么？"},
     "options":[{"en":"The top of the shell","zh":"龟壳的顶部"},{"en":"The part of the shell under the turtle's belly","zh":"龟腹下方的壳"},{"en":"A type of turtle","zh":"一种海龟"},{"en":"The head","zh":"头部"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines plastron as 'the part of a turtle's shell underneath its belly.'","zh":"词汇表将plastron定义为“海龟腹下方的壳”。"}},
    {"q":{"en":"How are leatherbacks different from other sea turtles?","zh":"棱皮龟与其他海龟有何不同？"},
     "options":[{"en":"They live only on land","zh":"它们只生活在陆地"},{"en":"They are covered with leathery skin and have a shell of cartilage, not bony plates","zh":"它们覆盖着革质皮肤，壳由软骨而非骨板构成"},{"en":"They have no shell at all","zh":"它们根本没有壳"},{"en":"They are the smallest","zh":"它们是最小的"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says the leatherback 'is covered with leathery skin' with a shell made of cartilage, unlike others with bony scutes.","zh":"书中说棱皮龟“覆盖着革质皮肤”，壳由软骨构成，不同于其他有骨板的海龟。"}},
    {"q":{"en":"What do adult green sea turtles eat?","zh":"成年绿海龟吃什么？"},
     "options":[{"en":"Jellyfish","zh":"水母"},{"en":"Plants (they are herbivorous)","zh":"植物（它们是草食性的）"},{"en":"Crabs","zh":"螃蟹"},{"en":"Fish","zh":"鱼"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book states, 'Green sea turtles are herbivorous as adults.'","zh":"书中说：“绿海龟成年后是草食性的。”"}},
    {"q":{"en":"How many eggs does a female sea turtle lay?","zh":"一只雌性海龟会产多少枚卵？"},
     "options":[{"en":"2 to 5","zh":"2到5枚"},{"en":"50 to 200","zh":"50到200枚"},{"en":"1,000","zh":"1000枚"},{"en":"None","zh":"不产卵"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says, 'Depending on the species, she may lay between 50 and 200 eggs.'","zh":"书中说：“根据种类不同，她可能产下50到200枚卵。”"}},
    {"q":{"en":"Why do more female hatchlings come from hot sand?","zh":"为什么在炎热的沙中会孵出更多雌性幼龟？"},
     "options":[{"en":"The mother chooses","zh":"由母亲选择"},{"en":"The temperature of the sand determines the sex—hot sand makes more females","zh":"沙的温度决定性别——热沙会产生更多雌性"},{"en":"Males dig out first","zh":"雄性先挖出来"},{"en":"It is random","zh":"这是随机的"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says, 'Hot sand produces more females, and cool sand produces more males.'","zh":"书中说：“热沙产生更多雌性，凉沙产生更多雄性。”"}},
    {"q":{"en":"How is this book mainly organized?","zh":"本书主要按什么方式组织内容？"},
     "options":[{"en":"In alphabetical order","zh":"按字母顺序"},{"en":"By topics: types, appearance, nesting, hazards, and protection","zh":"按主题：种类、外形、筑巢、危险与保护"},{"en":"By the turtle's age","zh":"按海龟的年龄"},{"en":"By ocean","zh":"按大洋"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The table of contents lists Types, Physical Appearance, Nesting, Hazards, and Protecting Sea Turtles.","zh":"目录列出了种类、外形、筑巢、危险以及保护海龟等主题。"}},
    {"q":{"en":"What is a Turtle Excluder Device (TED)?","zh":"“海龟排除装置”（TED）是什么？"},
     "options":[{"en":"A type of turtle","zh":"一种海龟"},{"en":"A trap door in shrimp nets that lets sea turtles escape","zh":"虾网中的一个活门，让海龟得以逃脱"},{"en":"A beach sign","zh":"一块海滩告示牌"},{"en":"A kind of boat","zh":"一种船"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says a TED is 'a trap door inside the shrimp net that allows sea turtles to escape.'","zh":"书中说，TED是“虾网内的一个活门，让海龟得以逃脱”。"}},
    {"q":{"en":"What does the author hope will happen to sea turtles?","zh":"作者希望海龟的命运如何？"},
     "options":[{"en":"They will become pets","zh":"它们会成为宠物"},{"en":"Enough people will care to protect their habitats and help them survive","zh":"足够多的人会关心并保护它们的栖息地，帮助它们生存下去"},{"en":"They will all move to zoos","zh":"它们都会搬到动物园"},{"en":"Fishing will increase","zh":"捕鱼会增加"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book hopes 'enough people will care about sea turtles to preserve their habitats and help them to survive.'","zh":"书中希望“有足够多的人关心海龟，保护它们的栖息地，帮助它们生存下去”。"}},
    {"q":{"en":"What is the biggest danger to sea turtles today?","zh":"当今海龟面临的最大危险是什么？"},
     "options":[{"en":"Sharks","zh":"鲨鱼"},{"en":"Human impact (habitat loss, trash, boat strikes)","zh":"人类的影响（栖息地丧失、垃圾、船只撞击）"},{"en":"Cold water","zh":"冷水"},{"en":"Other turtles","zh":"其他海龟"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says, 'The most serious dangers to all kinds of sea turtles come from human impact.'","zh":"书中说：“对所有海龟最严重的威胁都来自人类的影响。”"}}
  ],
  "extended":{
    "prompt":{"en":"Pick one sea turtle species from the book and write about where it lives and one special feature it has.","zh":"从书中选择一种海龟，写一写它生活在哪里，以及它的一个特殊特征。"},
    "guidance":{"en":["Name the species (e.g., leatherback, green, hawksbill).","Describe its habitat and one identifying feature."],
               "zh":["说出物种名称（如棱皮龟、绿海龟、玳瑁）。","描述它的栖息地和一项辨识特征。"]}
  }
})

# 8. Scaredy Camp
books.append({
  "slug": "scaredy-camp",
  "title": "Scaredy Camp",
  "titleZh": "胆小鬼露营",
  "level": "R",
  "genre": "Fiction",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"Who is the narrator of the story?","zh":"这个故事的叙述者是谁？"},
     "options":[{"en":"Sarah","zh":"萨拉"},{"en":"Qynn, Sarah's friend","zh":"奎恩，萨拉的朋友"},{"en":"Mr. Martinez","zh":"马丁内斯先生"},{"en":"A bear","zh":"一只熊"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The story is told by Sarah's friend ('Sarah and I are drifting off'); later she is called Qynn.","zh":"故事由萨拉的朋友讲述（“萨拉和我渐渐入睡”）；后文称她为奎恩。"}},
    {"q":{"en":"What is a 'dad joke' in this story?","zh":"在这个故事中，什么是“dad joke”（爸爸的冷笑话）？"},
     "options":[{"en":"A serious warning","zh":"一个严肃的警告"},{"en":"A mild, not-very-funny joke a father makes","zh":"父亲开的一个平淡、不太好笑的玩笑"},{"en":"A scary story","zh":"一个恐怖故事"},{"en":"A camping rule","zh":"一条露营规则"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"Sarah's dad joked about 'a voracious bear,' and she said 'Not funny, Dad'—he called it a 'dad joke.'","zh":"萨拉的父亲开玩笑说有“一只贪吃的熊”，萨拉说“一点不好笑，爸爸”——他称之为“爸爸的冷笑话”。"}},
    {"q":{"en":"What do the girls find on top of their tent?","zh":"两个女孩在帐篷顶上发现了什么？"},
     "options":[{"en":"Bear footprints","zh":"熊的脚印"},{"en":"Small streaked muddy handprints","zh":"小小的、有条纹的泥手印"},{"en":"Leaves","zh":"树叶"},{"en":"A lantern","zh":"一盏灯笼"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"They find the tent 'covered in small, streaked, muddy handprints, as if children were pawing at our tent.'","zh":"她们发现帐篷上“满是小小的、有条纹的泥手印，仿佛是孩子们扒着帐篷留下的”。"}},
    {"q":{"en":"What do the muddy handprints and the old lantern suggest?","zh":"泥手印和旧灯笼暗示了什么？"},
     "options":[{"en":"A bear visited","zh":"一只熊来过"},{"en":"Children (or something childlike) had been playing around the tent","zh":"有孩子（或具有孩子特征的事物）曾在帐篷周围玩耍"},{"en":"Sarah's dad did it","zh":"是萨拉的父亲干的"},{"en":"It rained inside","zh":"里面下过雨"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The handprints 'as if children were pawing' and a lantern that 'wasn't there when we arrived' hint at childlike visitors.","zh":"手印“仿佛是孩子们扒着留下的”，以及“我们到达时还没有”的灯笼，暗示有孩子般的访客。"}},
    {"q":{"en":"What did the narrator find hanging from a branch overhead?","zh":"叙述者在头顶的树枝上发现了什么？"},
     "options":[{"en":"A fishing rod","zh":"一根鱼竿"},{"en":"An old oil lantern","zh":"一盏旧的油灯"},{"en":"A flashlight","zh":"一支手电筒"},{"en":"A bird","zh":"一只鸟"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The bright beam 'reveals an old-looking lantern suspended from the branch. It wasn't there when we arrived.'","zh":"光束“照出树枝上挂着一盏旧油灯。我们到达时它并不在那里。”"}},
    {"q":{"en":"What feeling does the author mainly create in this story?","zh":"作者在这个故事中主要营造了什么感觉？"},
     "options":[{"en":"Excitement about sports","zh":"对运动的兴奋"},{"en":"Suspense and fear (being scared at camp)","zh":"悬念与恐惧（在营地里的害怕）"},{"en":"Happiness about a party","zh":"对聚会的开心"},{"en":"Anger","zh":"愤怒"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The title 'Scaredy Camp' and the scary nighttime events build suspense and fear.","zh":"标题“胆小鬼露营”以及夜晚的恐怖事件营造出悬念与恐惧。"}},
    {"q":{"en":"The story is told in...","zh":"这个故事采用……叙述。"},
     "options":[{"en":"First person by the narrator","zh":"叙述者的第一人称"},{"en":"Third person about Sarah only","zh":"仅关于萨拉的第三人称"},{"en":"Second person","zh":"第二人称"},{"en":"Newspaper style","zh":"新闻报道风格"}],
     "answer":0,"skill":"Craft and Structure",
     "explain":{"en":"The narrator uses 'I' and 'Sarah and I,' so it is first-person point of view.","zh":"叙述者使用“我”和“萨拉和我”，因此是是第一人称视角。"}},
    {"q":{"en":"What was the weather like when they arrived at the campsite?","zh":"她们到达营地时天气如何？"},
     "options":[{"en":"Sunny","zh":"晴天"},{"en":"A downpour (rain) started","zh":"开始下倾盆大雨"},{"en":"Snowing","zh":"下雪"},{"en":"Windy but dry","zh":"有风但干燥"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says, 'The downpour started as soon as we arrived at the campsite.'","zh":"书中说：“我们一到营地，倾盆大雨就开始了。”"}},
    {"q":{"en":"Why does Sarah's dad say he didn't hear the tent shaking?","zh":"为什么萨拉的父亲说他没听到帐篷摇晃？"},
     "options":[{"en":"He was outside","zh":"他在外面"},{"en":"He was sound asleep before they screamed","zh":"在她们尖叫前他已熟睡"},{"en":"There was no shaking","zh":"根本没有摇晃"},{"en":"He had earplugs","zh":"他戴了耳塞"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"He says, 'I didn't hear anything, but I was sound asleep before you started screeching.'","zh":"他说：“我什么也没听到，但在你们开始尖叫前我已经熟睡了。”"}},
    {"q":{"en":"What makes the ending mysterious?","zh":"是什么让结局显得神秘？"},
     "options":[{"en":"They caught the bear","zh":"她们抓住了熊"},{"en":"They found clues (lantern, handprints, a child's figure) but never learned who or what caused them","zh":"她们发现了线索（灯笼、手印、一个孩子的身影），却始终不知道是谁或是什么造成的"},{"en":"Sarah's dad confessed","zh":"萨拉的父亲承认了"},{"en":"The tent blew away","zh":"帐篷被吹走了"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The story ends with unexplained clues—a lantern, muddy handprints, and a child's figure by the shore.","zh":"故事以未解开的线索收尾——灯笼、泥手印，以及岸边一个孩子的身影。"}}
  ],
  "extended":{
    "prompt":{"en":"Write your own ending to the story. Who or what do you think caused the scraping, the shaking, and the muddy handprints?","zh":"为这个故事写一个你自己的结尾。你认为是什么（或谁）造成了刮擦声、帐篷摇晃和泥手印？"},
    "guidance":{"en":["Make a guess based on clues in the story (lantern, handprints, child's figure).","Explain why your idea fits the mystery."],
               "zh":["根据故事中的线索（灯笼、手印、孩子的身影）做出猜测。","解释为什么你的想法符合这个谜团。"]}
  }
})

# 9. Rattlers
books.append({
  "slug": "rattlers",
  "title": "Rattlers",
  "titleZh": "响尾蛇",
  "level": "R",
  "genre": "Informational",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"What do rattlesnakes eat that helps humans?","zh":"响尾蛇吃什麼对人类有益？"},
     "options":[{"en":"Birds","zh":"鸟"},{"en":"Rodents like rats and mice","zh":"老鼠之类的啮齿动物"},{"en":"Plants","zh":"植物"},{"en":"Fish","zh":"鱼"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says rattlers 'eat rodents such as rats and mice' and 'help humans by keeping the number of rodents under control.'","zh":"书中说响尾蛇“吃老鼠之类的啮齿动物”，并“通过控制啮齿动物数量来帮助人类”。"}},
    {"q":{"en":"A 'pit viper' is a snake that...","zh":"“pit viper”（颊窝毒蛇）是指……的蛇。"},
     "options":[{"en":"Lives in water","zh":"生活在水中"},{"en":"Has heat-sensing pits on its head that detect heat","zh":"头部有能探测热量的颊窝"},{"en":"Has no fangs","zh":"没有毒牙"},{"en":"Eats plants","zh":"吃植物"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines pit vipers as 'snakes that have pits on their heads that detect heat.'","zh":"词汇表将pit vipers定义为“头部有能探测热量的颊窝的蛇”。"}},
    {"q":{"en":"How do rattlesnakes MOST commonly move?","zh":"响尾蛇最普遍的移动方式是什么？"},
     "options":[{"en":"Sidewinding","zh":"侧向爬行"},{"en":"Serpentine (S-shaped) motion","zh":"蛇形（S形）运动"},{"en":"Jumping","zh":"跳跃"},{"en":"Rolling","zh":"翻滚"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the serpentine method 'is the most common' way rattlesnakes move.","zh":"书中说，蛇形运动方式是响尾蛇“最普遍”的移动方式。"}},
    {"q":{"en":"How are baby rattlers more dangerous than adults?","zh":"为什么幼响尾蛇比成年蛇更危险？"},
     "options":[{"en":"They are bigger","zh":"它们更大"},{"en":"They have no rattles to warn and less control over venom","zh":"它们没有响尾发出警告，且对毒液的控制力更弱"},{"en":"They do not bite","zh":"它们不咬人"},{"en":"They are slower","zh":"它们更慢"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says babies 'do not have rattles' to warn and 'have less control over how much venom they inject.'","zh":"书中说幼蛇“没有响尾”发出警告，且“对注入毒液的量控制力更弱”。"}},
    {"q":{"en":"What happens each time a rattler sheds its skin?","zh":"响尾蛇每蜕一次皮会发生什么？"},
     "options":[{"en":"It grows a new fang","zh":"长出一颗新毒牙"},{"en":"A section is added to its rattle","zh":"它的响尾会增加一节"},{"en":"It changes color","zh":"它改变颜色"},{"en":"It hibernates","zh":"它冬眠"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says each time the snake molts, 'a section of hollow ... material is left behind on its tail'—the rattle grows.","zh":"书中说，蛇每次蜕皮，“尾端会留下一节中空的……物质”——响尾随之增长。"}},
    {"q":{"en":"What is the author's attitude toward rattlesnakes?","zh":"作者对响尾蛇持什么态度？"},
     "options":[{"en":"They should all be killed","zh":"它们都应该被杀死"},{"en":"They are useful and should be understood and protected, not feared","zh":"它们有益，应被理解并加以保护，而非畏惧"},{"en":"They are harmless toys","zh":"它们是无害的玩具"},{"en":"Only experts should care","zh":"只有专家才应在意"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book stresses the good rattlers do and asks readers to 'respect these animals' and protect them.","zh":"本书强调响尾蛇的贡献，并呼吁读者“尊重这些动物”并加以保护。"}},
    {"q":{"en":"The book gives safety tips mainly to...","zh":"本书给出安全提示主要是为了……"},
     "options":[{"en":"Teach readers how to catch snakes","zh":"教读者如何抓蛇"},{"en":"Explain how to avoid bites and what to do if bitten","zh":"说明如何避免被咬，以及被咬后该怎么办"},{"en":"Describe snake venom","zh":"描述蛇毒"},{"en":"Sell antivenom","zh":"出售抗毒血清"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"Sections titled 'Rattlesnake Safety' tell how to avoid bites and steps to follow if someone is bitten.","zh":"题为“响尾蛇安全”的章节说明了如何避免被咬，以及被咬后应采取的步骤。"}},
    {"q":{"en":"Where are the greatest numbers of rattlesnakes found?","zh":"响尾蛇数量最多的地方是哪里？"},
     "options":[{"en":"Rainforests of Brazil","zh":"巴西的热带雨林"},{"en":"Deserts and dry areas of the southwestern US and northern Mexico","zh":"美国西南部和墨西哥北部的沙漠及干旱地区"},{"en":"The Arctic","zh":"北极"},{"en":"Australia","zh":"澳大利亚"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says the greatest numbers are 'in the deserts and dry areas of the southwestern United States and northern Mexico.'","zh":"书中说，数量最多的是“美国西南部和墨西哥北部的沙漠及干旱地区”。"}},
    {"q":{"en":"Why does the author mention that antivenom comes from horses?","zh":"作者为什么要提到抗毒血清来自马？"},
     "options":[{"en":"To show horses are dangerous","zh":"为了说明马很危险"},{"en":"To explain how snakebite medicine is made","zh":"为了解释蛇咬伤药物是如何制成的"},{"en":"To say horses get bitten","zh":"为了说马会被咬"},{"en":"To describe farming","zh":"为了描述农业"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The 'Do You Know?' note explains doctors inject a horse with venom so it builds a chemical that stops the poison in people.","zh":"“你知道吗？”说明医生给马注射少量毒液，使其产生能抑制人体毒性的化学物质。"}},
    {"q":{"en":"What is the main message about the rattler's future?","zh":"关于响尾蛇的未来，主要信息是什么？"},
     "options":[{"en":"They will take over the world","zh":"它们将统治世界"},{"en":"People should respect and protect them as habitats shrink","zh":"随着栖息地缩减，人们应尊重并保护它们"},{"en":"Roundups should increase","zh":"围捕活动应该增加"},{"en":"They are already extinct","zh":"它们已经灭绝"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The book says 'If we respect these animals, they will not hurt us' and urges protecting their habitats.","zh":"书中说“如果我们尊重这些动物，它们就不会伤害我们”，并呼吁保护它们的栖息地。"}}
  ],
  "extended":{
    "prompt":{"en":"Create a safety poster tip for people who hike in rattlesnake country. What should they do, and what should they not do?","zh":"为在响尾蛇出没地区徒步的人制作一条安全提示。他们应该做什么，不应该做什么？"},
    "guidance":{"en":["List one 'do' (e.g., wear boots, back away slowly).","List one 'don't' (e.g., don't bother the snake, don't put hands under rocks)."],
               "zh":["列出一条“应该做”的（如穿靴子、缓慢后退）。","列出一条“不应该做”的（如不要招惹蛇、不要把收伸到石头下）。"]}
  }
})

# 10. Robin Hood Wins the Sheriff's Golden Arrow
books.append({
  "slug": "robin-hood-wins-the-sheriff-s-golden-arrow",
  "title": "Robin Hood Wins the Sheriff's Golden Arrow",
  "titleZh": "罗宾汉赢得郡长的金箭",
  "level": "R",
  "genre": "Folktale",
  "mainSkill": "Key Ideas and Details",
  "questions": [
    {"q":{"en":"Where did Robin Hood and his Merry Men live?","zh":"罗宾汉和他的快乐伙伴住在哪里？"},
     "options":[{"en":"Nottingham Castle","zh":"诺丁汉城堡"},{"en":"Deep in Sherwood Forest","zh":"舍伍德森林深处"},{"en":"A village","zh":"一个村庄"},{"en":"London","zh":"伦敦"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"The book says Robin Hood lived with his band 'deep inside Sherwood Forest.'","zh":"书中说，罗宾汉与他的队伍住在“舍伍德森林深处”。"}},
    {"q":{"en":"In the story, the word 'duped' means...","zh":"在故事中，“duped”（上当）一词的意思是……"},
     "options":[{"en":"Helped","zh":"帮助"},{"en":"Tricked","zh":"被欺骗"},{"en":"Praised","zh":"称赞"},{"en":"Arrested","zh":"被捕"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"The glossary defines duped as 'tricked.'","zh":"词汇表将duped定义为“被欺骗”。"}},
    {"q":{"en":"How did Robin Hood avoid being arrested by the Sheriff's guard?","zh":"罗宾汉是如何避免被郡长的卫兵逮捕的？"},
     "options":[{"en":"He fought him","zh":"他与卫兵打斗"},{"en":"He fed the guard until he fell asleep and stole the warrant","zh":"他让卫兵吃撑到睡着，然后偷走了逮捕令"},{"en":"He ran away","zh":"他逃跑了"},{"en":"He paid him","zh":"他付钱给卫兵"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"Robin 'invited the guard to a feast'; the guard 'ate too much and fell asleep,' so Robin stole the warrant.","zh":"罗宾汉“邀请卫兵赴宴”；卫兵“吃得太多睡着了”，于是罗宾偷走了逮捕令。"}},
    {"q":{"en":"Why did Robin disguise himself as a beggar?","zh":"罗宾汉为什么要伪装成乞丐？"},
     "options":[{"en":"He was poor","zh":"他很穷"},{"en":"So the Sheriff would not recognize him at the archery festival","zh":"为了不让郡长在射箭比赛上认出他"},{"en":"He lost his clothes","zh":"他弄丢了衣服"},{"en":"To beg for food","zh":"为了讨饭"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"Robin colored his hair with walnut stain and wore a patch and ragged clothes so the Sheriff 'did not recognize him.'","zh":"罗宾汉用核桃渍染发、戴上眼罩、穿上破衣，因此郡长“没有认出他”。"}},
    {"q":{"en":"Who won the gold-covered arrow at the archery festival?","zh":"在射箭比赛上，谁赢得了镀金箭？"},
     "options":[{"en":"Gill o' the Red Cap","zh":"红帽吉尔"},{"en":"The Sheriff","zh":"郡长"},{"en":"Robin Hood (disguised as a beggar)","zh":"罗宾汉（伪装成乞丐）"},{"en":"Adam o' the Dell","zh":"山谷亚当"}],
     "answer":2,"skill":"Key Ideas and Details",
     "explain":{"en":"The 'tattered beggar'—Robin in disguise—shot the center and 'won the gold-covered arrow.'","zh":"那个“衣衫褴褛的乞丐”（伪装的罗宾）射中靶心，“赢得了镀金箭”。"}},
    {"q":{"en":"Why did the Sheriff hold the archery festival?","zh":"郡长为什么要举办射箭比赛？"},
     "options":[{"en":"To celebrate Robin Hood","zh":"为了庆祝罗宾汉"},{"en":"To trap and catch Robin Hood","zh":"为了设陷阱抓住罗宾汉"},{"en":"To teach archery","zh":"为了教授射箭"},{"en":"To give away gold","zh":"为了分发黄金"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"The Sheriff said, 'I'll catch him by trickery... When he comes, I'll arrest and hang him.'","zh":"郡长说：“我要用计谋抓住他……等他一来，我就逮捕并绞死他。”"}},
    {"q":{"en":"What trait best describes Robin Hood in this tale?","zh":"在故事中，哪个特质最能描述罗宾汉？"},
     "options":[{"en":"Cruel and greedy","zh":"残忍而贪婪"},{"en":"A clever outlaw who helps the poor","zh":"一个帮助穷人的聪明亡命之徒"},{"en":"A coward","zh":"一个懦夫"},{"en":"A farmer","zh":"一个农民"}],
     "answer":1,"skill":"Craft and Structure",
     "explain":{"en":"Robin 'stole back the gold taken in unjust taxes' and gave it to the poor, and used clever disguises.","zh":"罗宾汉“夺回被不公征税夺走的金子”分给穷人，并使用了巧妙的伪装。"}},
    {"q":{"en":"How did the common people and the Sheriff's enemies view Robin differently?","zh":"普通百姓和郡长的敌人对罗宾的看法有何不同？"},
     "options":[{"en":"Both hated him","zh":"两人都恨他"},{"en":"Enemies saw him as a hated robber; common folk saw him as a beloved hero","zh":"敌人视他为可恨的强盗；百姓视他为受人爱戴的英雄"},{"en":"Both loved him","zh":"两人都爱戴他"},{"en":"No one cared","zh":"没有人关心"}],
     "answer":1,"skill":"Integration of Knowledge and Ideas",
     "explain":{"en":"The book says, 'To his enemies, Robin and his men were hated robbers. To the common folk they helped, they were beloved heroes.'","zh":"书中说：“对敌人而言，罗宾和他的手下是可恨的强盗；对被他们帮助的百姓而言，他们是受人爱戴的英雄。”"}},
    {"q":{"en":"How did Robin let the Sheriff know he had won?","zh":"罗宾汉如何让郡长知道是他赢了？"},
     "options":[{"en":"He sent a letter by mail","zh":"他邮寄了一封信"},{"en":"He shot an arrow with a note through the window into the Sheriff's roast","zh":"他射出一支带字条的箭，穿过窗户扎进郡长的烤肉里"},{"en":"He visited the Sheriff","zh":"他亲自拜访郡长"},{"en":"Little John told him","zh":"小约翰告诉了他"}],
     "answer":1,"skill":"Key Ideas and Details",
     "explain":{"en":"A 'shaft flew through the window. It stuck straight into the roast' with a note saying the beggar was Robin Hood.","zh":"“一支箭飞进窗户，直直扎进烤肉里”，附带的字条说明那个乞丐就是罗宾汉。"}},
    {"q":{"en":"What kind of story is this, and what does it admire?","zh":"这是一个关于什么的故事，它赞美了什么？"},
     "options":[{"en":"A news report about archery","zh":"一篇关于射箭的新闻报道"},{"en":"A folktale that admires Robin's cleverness and fairness to the poor","zh":"一个赞美罗宾的机智和对穷人公平的民间传说"},{"en":"A science book","zh":"一本科普书"},{"en":"A history of England","zh":"一部英国史"}],
     "answer":1,"skill":"Author's Purpose and Perspective",
     "explain":{"en":"It is 'An English Folktale' that celebrates Robin Hood's cleverness and his giving to the poor.","zh":"这是“一则英国民间传说”，歌颂了罗宾汉的机智以及他分给穷人的义举。"}}
  ],
  "extended":{
    "prompt":{"en":"Robin Hood gave gold back to the poor. Write about a time you think it is fair to share or give something to someone else.","zh":"罗宾汉把金子还给了穷人。写一写你认为把东西分享或赠予他人是公平合理的一种情形。"},
    "guidance":{"en":["Describe the situation you have in mind.","Explain why sharing or giving was the right thing to do."],
               "zh":["描述你想到的情况。","解释为什么分享或给予是正确的做法。"]}
  }
})

for b in books:
    path = os.path.join(OUT, b["slug"] + ".json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(b, f, ensure_ascii=False, indent=2)
    print("wrote", path)
print("DONE", len(books))
